---
title: "Another Round Experiment"
author: "Xinwei"
date: "7/31/2020"
output: 
 html_document:
     toc: true
     toc_depth: 3   
     theme: united
     number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
library(CVXR)
library(MASS)
library(R.matlab)
library(e1071)
library(kernlab)
library(glmnet)
library(ggpubr)
library(truncnorm)
library(ggplot2)
rm(list=ls())
setwd("~/Desktop/Multiclass Classification/MSVM Code")
source("primary form functions.R")
source("kernel primary form functions.R")


plot_batch <- function(train_data, test_data, C, lambda, intercept = T){
    
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(WW_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("WW:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(CS_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("CS:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.2 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C= 1, lambda=0, intercept = T)
  predicted_label <- predict(Duchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Duchi:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.3 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MDuchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MDuchi:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.4 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)
  


  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.1 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
    
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.2 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.3 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
  



  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.1 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
 
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.2 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.3 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  # 
  g4.1 <- tryCatch({
  LLW_fit <- LLW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(LLW_fit, test_data$X)
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  return(plot_decision_boundary(LLW_fit, print = F, title = title, rule = "dagger"))
  }, error = function(e){ NULL})
  
  OVA_fit <- OVA_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(OVA_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("OVA:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.2 <- plot_decision_boundary(OVA_fit, print = F, title = title)
  
  
  
  
  MSVM8_fit <- MSVM8_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MSVM8_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM8:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.3 <- plot_decision_boundary(MSVM8_fit, print = F, title = title)
  
  fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = T)
  Multinom_fit <- MDuchi_fit
  Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
  predicted_label <- predict(Multinom_fit, test_data$X)
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Multinom:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.4 <- plot_decision_boundary(Multinom_fit, print = F, title = title)

  
  MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.1 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.2 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.3 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
  
  ggarrange(g1.1, g1.2, g1.3, g1.4,
            g2.1, g2.2, g2.3, NULL,
            g3.1, g3.2, g3.3, NULL,
            g4.1, g4.2, g4.3, g4.4,
            g5.1, g5.2, g5.3, NULL, ncol=4, nrow = 5, common.legend = TRUE, legend="bottom")
  

}

```

# Three-class Gaussian Weakly Separable


```{r echo=F}

generate_noise_three_gaussian <- function(n, sep = 2){
  
  t <- sample(seq(1,3), size = n, replace = T)

  dat <- t(sapply(t , function(z){
    if(z==1){
      x <- mvrnorm(1,c(1,0), sep^2*diag(1,2))
    }else if(z==2){
      x <- mvrnorm(1,c(-1,2), sep^2*diag(1,2))
    }else if(z==3){
      x <- mvrnorm(1,c(-1,-2), sep^2*diag(1,2))
    }
    
    if(z==1){
      y = sample(seq(1,3), size=1, prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(seq(1,3), size=1, prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(seq(1,3), size=1, prob= c(.15, .3, .45))
    }
    
    return(c(x,y))
  }))  
  
  X <- dat[,1:2]
  y <- dat[,3]

  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}


```

## Sep sigma = sqrt(2)/2

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}
set.seed(134)
n = 1500
sep <-  sqrt(2)/2
train_data <- generate_noise_three_gaussian(n, sep =sep)
test_data <- generate_noise_three_gaussian(100000, sep = sep)

plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = 2/3*sqrt(2)

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}
set.seed(134)
n = 1500
sep <-  2*sqrt(2)/3
train_data <- generate_noise_three_gaussian(n, sep =sep)
test_data <- generate_noise_three_gaussian(100000, sep = sep)

plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = sqrt(2)

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

n = 1500
sep <-  sqrt(2)
train_data <- generate_noise_three_gaussian(n, sep =sep)
test_data <- generate_noise_three_gaussian(100000, sep = sep)

plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = 2*sqrt(2)

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

n = 1500
sep <-  2*sqrt(2)
train_data <- generate_noise_three_gaussian(n, sep =sep)
test_data <- generate_noise_three_gaussian(100000, sep = sep)

plot_batch(train_data, test_data, C=1, lambda = 0)
```



# Four-class Gaussian Weakly Separable
```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

generate_noise_four_gaussian <- function(n, sep = 2){
  
 
  t <- sample(seq(1,4), size = n, replace = T)

  dat <- t(sapply(t , function(z){
    if(z==1){
      x <- mvrnorm(1,c(2,0), sep^2*diag(1,2))
    }else if(z==2){
      x <- mvrnorm(1,c(0,2), sep^2*diag(1,2))
    }else if(z==3){
      x <- mvrnorm(1,c(0,-2), sep^2*diag(1,2))
    }else if(z==4){
      x <- mvrnorm(1,c(-2,0) , sep^2*diag(1,2))
    }
    
    
    if(z==1){
      y = sample(seq(1,4), size=1, prob= c(1, 0, 0, 0))
    }else if(z==2){
      y = sample(seq(1,4), size=1, prob= c(0, 1, 0, 0))
    }else if(z==3){
      y = sample(seq(1,4), size=1, prob= c(0, 0, 1, 0))
    }else if(z==4){
      y = sample(seq(1,4), size=1, prob= c(0, 0, 0, 1))
    }
    
    return(c(x,y))
  }))  
  
  X <- dat[,1:2]
  y <- dat[,3]

  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}


plot_batch <- function(train_data, test_data, C, lambda, intercept = T){
    
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(WW_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("WW:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(CS_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("CS:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.2 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C= 1, lambda=0, intercept = T)
  predicted_label <- predict(Duchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Duchi:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.3 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MDuchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MDuchi:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.4 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)
  


  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.1 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
    
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.2 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.3 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
    
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 4)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.4 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
  

  fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = T)
  Multinom_fit <- MDuchi_fit
  Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
  predicted_label <- predict(Multinom_fit, test_data$X)
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Multinom:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.4 <- plot_decision_boundary(Multinom_fit, print = F, title = title)


  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.1 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
 
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.2 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.3 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 4)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.4 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  # 
  g4.1 <- tryCatch({
  LLW_fit <- LLW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(LLW_fit, test_data$X)
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  return(plot_decision_boundary(LLW_fit, print = F, title = title, rule = "dagger"))
  }, error = function(e){ NULL})
  
  OVA_fit <- OVA_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(OVA_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("OVA:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.2 <- plot_decision_boundary(OVA_fit, print = F, title = title)
  
  
  
  
  MSVM8_fit <- MSVM8_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MSVM8_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM8:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.3 <- plot_decision_boundary(MSVM8_fit, print = F, title = title)
  
  
  MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.1 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.2 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.3 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
    
   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 4)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.4 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
  ggarrange(g1.1, g1.2, g1.3, g1.4,
            g2.1, g2.2, g2.3, g2.4,
            g3.1, g3.2, g3.3, g3.4,
            g4.1, g4.2, g4.3, g4.4,
            g5.1, g5.2, g5.3, g5.4, ncol=4, nrow = 5, common.legend = TRUE, legend="bottom")
  

}

```

## Sep sigma = sqrt(2)/2

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

set.seed(134)
n = 2000
sep <-  sqrt(2)/2
train_data <- generate_noise_four_gaussian(n, sep =sep)
test_data <- generate_noise_four_gaussian(100000, sep = sep)

plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = 2/3*sqrt(2)

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

n = 2000
sep <-  2*sqrt(2)/3
train_data <- generate_noise_four_gaussian(n, sep =sep)
test_data <- generate_noise_four_gaussian(100000, sep = sep)

plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = sqrt(2)


```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

n = 2000
sep <-  sqrt(2)
train_data <- generate_noise_four_gaussian(n, sep =sep)
test_data <- generate_noise_four_gaussian(100000, sep = sep)
plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = 2*sqrt(2)

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

n = 2000
sep <-  2*sqrt(2)
train_data <- generate_noise_four_gaussian(n, sep =sep)
test_data <- generate_noise_four_gaussian(100000, sep = sep)
plot_batch(train_data, test_data, C=1, lambda = 0)
```




# Five-class Gaussian Weakly Separable

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

generate_noise_five_gaussian <- function(n, sep = 2){
  
 
  t <- sample(seq(1,5), size = n, replace = T)

  dat <- t(sapply(t , function(z){
    if(z==1){
      x <- mvrnorm(1,c(0,0), sep^2*diag(1,2))
    }else if(z==2){
      x <- mvrnorm(1,c(2*sqrt(2),0), sep^2*diag(1,2))
    }else if(z==3){
      x <- mvrnorm(1,c(0,2*sqrt(2)), sep^2*diag(1,2))
    }else if(z==4){
      x <- mvrnorm(1,c(-2*sqrt(2),0) , sep^2*diag(1,2))
    }else if(z==5){
      x <- mvrnorm(1,c(0,-2*sqrt(2)) , sep^2*diag(1,2))
    }
    
    
    if(z==1){
      y = sample(seq(1,5), size=1, prob= c(1, 0, 0, 0, 0))
    }else if(z==2){
      y = sample(seq(1,5), size=1, prob= c(0, 1, 0, 0, 0))
    }else if(z==3){
      y = sample(seq(1,5), size=1, prob= c(0, 0, 1, 0, 0))
    }else if(z==4){
      y = sample(seq(1,5), size=1, prob= c(0, 0, 0, 1, 0))
    }else if(z==5){
      y = sample(seq(1,5), size=1, prob= c(0, 0, 0, 0, 1))
    }
    
    
    return(c(x,y))
  }))  
  
  X <- dat[,1:2]
  y <- dat[,3]

  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}



plot_batch <- function(train_data, test_data, C, lambda, intercept = T){
    
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(WW_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("WW:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(CS_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("CS:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.2 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C= 1, lambda=0, intercept = T)
  predicted_label <- predict(Duchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Duchi:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.3 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MDuchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MDuchi:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.4 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)
  

  fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = T)
  Multinom_fit <- MDuchi_fit
  Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
  predicted_label <- predict(Multinom_fit, test_data$X)
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Multinom:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.5 <- plot_decision_boundary(Multinom_fit, print = F, title = title)


  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.1 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
    
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.2 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.3 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
    
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 4)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.4 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 5)
  predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.5 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
  
  

  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.1 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
 
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.2 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.3 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 4)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.4 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 5)
  predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.5 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
  
  # 
  # 
  g4.1 <- tryCatch({
  LLW_fit <- LLW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(LLW_fit, test_data$X)
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  return(plot_decision_boundary(LLW_fit, print = F, title = title, rule = "dagger"))
  }, error = function(e){ NULL})
  
  OVA_fit <- OVA_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(OVA_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("OVA:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.2 <- plot_decision_boundary(OVA_fit, print = F, title = title)
  
  
  
  
  MSVM8_fit <- MSVM8_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MSVM8_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM8:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.3 <- plot_decision_boundary(MSVM8_fit, print = F, title = title)
  
  
  MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.1 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.2 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.3 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
    
   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 4)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.4 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
     
  MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 4)
  predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.5 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
  
  ggarrange(g1.1, g1.2, g1.3, g1.4, g1.5,
            g2.1, g2.2, g2.3, g2.4, g2.5,
            g3.1, g3.2, g3.3, g3.4, g3.5,
            g4.1, g4.2, g4.3, NULL, NULL,
            g5.1, g5.2, g5.3, g5.4, g5.5, ncol=5, nrow = 5, common.legend = TRUE, legend="bottom")
  

}
```

## Sep sigma = sqrt(2)/2

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

set.seed(134)
n = 2500
sep <-  2*sqrt(2)/4
train_data <- generate_noise_five_gaussian(n, sep =sep)
test_data <- generate_noise_five_gaussian(100000, sep = sep)

plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = 2/3*sqrt(2)

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

n = 2500
sep <-  2*sqrt(2)/3
train_data <- generate_noise_five_gaussian(n, sep =sep)
test_data <- generate_noise_five_gaussian(100000, sep = sep)

plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = sqrt(2)


```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

n = 2500
sep <-  sqrt(2)
train_data <- generate_noise_five_gaussian(n, sep =sep)
test_data <- generate_noise_five_gaussian(100000, sep = sep)
plot_batch(train_data, test_data, C=1, lambda = 0)
```

## Sep sigma = 2*sqrt(2)

```{r echo = F, fig.height=15, fig.width=12, warning = FALSE}

n = 2500
sep <-  2*sqrt(2)
train_data <- generate_noise_five_gaussian(n, sep =sep)
test_data <- generate_noise_five_gaussian(100000, sep = sep)
plot_batch(train_data, test_data, C=1, lambda = 0)
```