---
title: "3 points"
author: "Xinwei"
date: "6/17/2020"
output: html_document
---

````{r include = FALSE}
library(CVXR)
library(MASS)
set.seed(1223)
rm(list = ls())
setwd("~/Desktop/Multiclass Classification/MSVM Code")
source("~/Desktop/Multiclass Classification/MSVM Code/primary form functions.R")
source("~/Desktop/Multiclass Classification/MSVM Code/Dual form functions.R")
```

# Case 1
```{r fig.width = 6}
# X = rbind(c(-2,1),c(-2,-1),c(2,1)
n = 2000
Sigma <- diag(.01,2)
X1 <- mvrnorm(n,c(-2,1),Sigma)
X2 <- mvrnorm(n,c(-2,-1),Sigma)
X3 <- mvrnorm(n,c(2,1),Sigma)
X <- rbind(X1,X2,X3)
y <- c(rep(1,nrow(X1)),rep(2,nrow(X2)),rep(3,nrow(X3)))

C = 1
xlim = c( floor(min(X[,1]))-1, ceiling(max(X[,1]))+1)
ylim = c( floor(min(X[,2]))-1, ceiling(max(X[,2]))+1)

plot_nearest_neighbour_decision_boundary(X = rbind(c(-2,1),c(-2,-1),c(2,1)),y = c(1,2,3), dis = "L2", title = "Nearest Neighbour in L2", xlim = xlim, ylim = ylim)
plot_decision_boundary(X=rbind(c(-2,1),c(-2,-1),c(2,1)),y = c(1,2,3),beta = WW_pri_opt(X = rbind(c(-2,1),c(-2,-1),c(2,1)),y = c(1,2,3),C), title = "WW", xlim = xlim, ylim = ylim)

plot_decision_boundary(X,y,beta = WW_pri_opt(X, y, C), title = "WW", xlim = xlim, ylim = ylim)

```