---
title: "Example Plot"
author: "Xinwei"
date: "6/16/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

````{r include = FALSE}
library(CVXR)
library(MASS)
set.seed(1223)
rm(list = ls())
setwd("~/Desktop/Multiclass Classification/MSVM Code")
source("~/Desktop/Multiclass Classification/MSVM Code/primary form functions.R")
source("~/Desktop/Multiclass Classification/MSVM Code/Dual form functions.R")
```

```{r fig.width = 6}
X = rbind(c(-2,1),c(-2,-1),c(2,1))
y = c(1,2,3)
C = 1
Duchi_beta <- round(Duchi_pri_opt(X,y,C),3)
Duchi_Decision_beta  <- rbind(Duchi_beta[1,] - Duchi_beta[3,], Duchi_beta[2,] - Duchi_beta[3,], Duchi_beta[1,] - Duchi_beta[2,])
Duchi_Decision_beta

solve(Duchi_Decision_beta[1:2,1:2],Duchi_Decision_beta[1:2,3])

New1_beta <- round(New1_pri_opt(X,y,C),3)
rbind(New1_beta,
New1_beta[1,] - New1_beta[2,])

solve(New1_beta[,1:2],New1_beta[,3])


-c(New1_beta[2]/New1_beta[1], New1_beta[3]/New1_beta[1])

plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```



```{r fig.width = 6}
X = rbind(c(-2,1),c(2,1),c(-2,-1))
y = c(1,2,3)
C = 1
round(Duchi_pri_opt(X,y,C),3)
round(New1_pri_opt(X,y,C),3)
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```


```{r fig.width = 6}
X = rbind(c(2,1),c(-2,-1),c(-2,1))
y = c(1,2,3)
C = 1
round(Duchi_pri_opt(X,y,C),3)
round(New1_pri_opt(X,y,C),3)
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```