---
title: "Example plot 4 points"
author: "Xinwei"
date: "6/16/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

````{r include = FALSE}
library(CVXR)
library(MASS)
set.seed(1223)
rm(list = ls())
setwd("~/Desktop/Multiclass Classification/MSVM Code")
source("~/Desktop/Multiclass Classification/MSVM Code/primary form functions.R")
source("~/Desktop/Multiclass Classification/MSVM Code/Dual form functions.R")
```

# Case 1
```{r fig.width = 6}
X = rbind(c(-2,1),c(-2,-1),c(2,1),c(2,-1))
y = c(1,2,3,4)
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```



```{r fig.width = 6}
X = rbind(c(-2,1),c(-2,-1),c(2,-1),c(2,1))
y = c(1,2,3,4)
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```

```{r fig.width = 6}
X = rbind(c(-2,1),c(2,-1),c(2,1),c(-2,-1))
y = c(1,2,3,4)
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```


```{r fig.width = 6}
X = rbind(c(2,-1), c(2,1),c(-2,-1),c(-2,1))
y = c(1,2,3,4)
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```


# Case 2


```{r fig.width = 6}

X = rbind(c(-2,3),c(2,-2),c(2,1),c(-2,-4))
y = c(1,2,3,4)
plot_nearest_neighbour_decision_boundary(X, y, dis = "L1", title = "Nearest Neighbour in L1")
plot_nearest_neighbour_decision_boundary(X, y, dis = "L2", title = "Nearest Neighbour in L2")
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```


```{r fig.width = 6}
X = rbind(c(2,-2),c(2,1),c(-2,-4),c(-2,3))
y = c(1,2,3,4)
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```


```{r fig.width = 6}
X = rbind(c(2,1),c(-2,-4),c(-2,3),c(2,-2))
y = c(1,2,3,4)
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```



```{r fig.width = 6}
X = rbind(c(-2,-4),c(-2,3),c(2,-2),c(2,1))
y = c(1,2,3,4)
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```

# case 3



```{r fig.width = 6}
n = 500
Sigma <- diag(2,2)
X1 <- mvrnorm(n,c(-2,3),Sigma)
X2 <- mvrnorm(n,c(2,-2),Sigma)
X3 <- mvrnorm(n,c(2,1),Sigma)
X4 <- mvrnorm(n,c(-2,-4),Sigma)
X <- rbind(X1,X2,X3,X4)
y <- c(rep(1,nrow(X1)),rep(2,nrow(X2)),rep(3,nrow(X3)),rep(4,nrow(X3)))


plot_nearest_neighbour_decision_boundary(X = rbind(c(-2,3),c(2,-2),c(2,1),c(-2,-4)),  y = c(1,2,3,4), dis = "L1", title = "Nearest Neighbour in L1")
plot_nearest_neighbour_decision_boundary(X = rbind(c(-2,3),c(2,-2),c(2,1),c(-2,-4)),  y = c(1,2,3,4), dis = "L2", title = "Nearest Neighbour in L2")
C=  1
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0", dagger_rule = F)
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, Dagger", dagger_rule = T)
```