---
title: "Margin Analysis"
author: "Xinwei Zhang"
date: "July 15, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(CVXR)
library(MASS)
library(nnet)
library(parallel)
library(kernlab)
library(ggpubr)
library(ggplot2)
set.seed(12344)
rm(list = ls())
par(mfrow=c(1,1))
setwd("C:\\Users\\xz396\\Desktop\\Multiclass Classification\\MSVM Code")

source("primary form functions.R")

```

# Case 1

```{r echo=F, fig.width=8, fig.height=6}
generate_noise_circle <- function(n){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 2)
    }else if(z==2){
      xz <- runif(1, min = 2, max = 11)
    }else if(z==3){
      xz <- runif(1, min = 11, max = 20)
    }
    x = c(cos(xz*pi/10), sin(xz*pi/10))
  
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.5, 1/3, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.9, 0, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(1/3, .5, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.2, .7, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0.05, 0.05, .9))
      # y = sample(c(1,2,3), size=1,prob= c(1/6, 1/3, .5))
    }

    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}

plot_ridgeless_circle_boundary <- function(model, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max"){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  if(is.null(ylim)){
    ylim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  
  nd.r1 = seq(from = 0.5, 0.9, length.out = 100)

  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(0.97 * circ.x)
  colnames(circ.nd) <- c("x","y")
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  
  nd1$class <- rep(predict(model, nd.x, rule = rule),100)
 
  
  nd <-  nd1
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(0),cos(2/10*pi),cos(11/10*pi)), y1 = c(0,0,0), y2 = c(sin(0),sin(2/10*pi),sin(11/10*pi)))
  
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .5, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="blue","2"= "green", "3"="red"))
  
  # suppressWarnings(print(plt))
}


##############Three Class################

set.seed(123)
n <- 2000
oracle_data <- generate_noise_circle(10^5)
train_data <- generate_noise_circle(n)
# train_data$oracle_acc
WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

y <- train_data$y
X <- train_data$X
t <- train_data$t
class_idx <- sort(unique(y))
Y <- sapply(class_idx, function(id){as.numeric(y==id)})
m <- length(class_idx)

c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y))



WW_slack <- pmax(1-((cbind(train_data$X,1)%*%t(WW_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(WW_fit$beta)),0)
CS_slack <- pmax(1-((cbind(train_data$X,1)%*%t(CS_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(CS_fit$beta)),0)
Duchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(Duchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(Duchi_fit$beta)),0)
MDuchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(MDuchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(MDuchi_fit$beta)),0)


par(mfrow=c(3,4))
boxplot(WW_slack[y==1,-1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))


# par(mfrow=c(2,2))
boxplot(WW_slack[y==2,-2], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2,-2], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2,-2], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))
boxplot(MDuchi_slack[y==2,-2], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))

# par(mfrow=c(2,2))
boxplot(WW_slack[y==3,-3], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3,-3], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3,-3], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3,-3], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
```


```{r echo=F, fig.width=8, fig.height=2}
g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW")
g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS")
g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi")
g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi")
ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")

```

# Case 2

```{r echo=F, fig.width=8, fig.height=6}
generate_noise_circle <- function(n){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 5)
    }else if(z==2){
      xz <- runif(1, min = 5, max = 11)
    }else if(z==3){
      xz <- runif(1, min = 11, max = 20)
    }
    x = c(cos(xz*pi/10), sin(xz*pi/10))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.5, 1/3, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.9, 0, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(1/3, .5, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.2, .7, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0.05, 0.05, .9))
      # y = sample(c(1,2,3), size=1,prob= c(1/6, 1/3, .5))
    }

    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}


plot_ridgeless_circle_boundary <- function(model, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max"){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  if(is.null(ylim)){
    ylim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  
  nd.r1 = seq(from = 0.5, 0.9, length.out = 100)

  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(0.97 * circ.x)
  colnames(circ.nd) <- c("x","y")
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  
  nd1$class <- rep(predict(model, nd.x, rule = rule),100)
 
  
  nd <-  nd1
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(0),cos(5/10*pi),cos(11/10*pi)), y1 = c(0,0,0), y2 = c(sin(0),sin(5/10*pi),sin(11/10*pi)))
  
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .5, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="blue","2"= "green", "3"="red"))
  
  # suppressWarnings(print(plt))
}
##############Three Class################

set.seed(123)
n <- 2000
oracle_data <- generate_noise_circle(10^5)
train_data <- generate_noise_circle(n)
# train_data$oracle_acc
WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

y <- train_data$y
X <- train_data$X
t <- train_data$t
class_idx <- sort(unique(y))
Y <- sapply(class_idx, function(id){as.numeric(y==id)})
m <- length(class_idx)

c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y))



WW_slack <- pmax(1-((cbind(train_data$X,1)%*%t(WW_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(WW_fit$beta)),0)
CS_slack <- pmax(1-((cbind(train_data$X,1)%*%t(CS_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(CS_fit$beta)),0)
Duchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(Duchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(Duchi_fit$beta)),0)
MDuchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(MDuchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(MDuchi_fit$beta)),0)



par(mfrow=c(3,4))
boxplot(WW_slack[y==1,-1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2,-2], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2,-2], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2,-2], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))
boxplot(MDuchi_slack[y==2,-2], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))

boxplot(WW_slack[y==3,-3], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3,-3], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3,-3], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3,-3], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
```


```{r echo=F, fig.width=8, fig.height=2}

g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW")
g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS")
g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi")
g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi")
ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")

```



# Case 3

```{r echo=F, fig.width=8, fig.height=6}
generate_noise_circle <- function(n){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 6)
    }else if(z==2){
      xz <- runif(1, min = 6, max = 13)
    }else if(z==3){
      xz <- runif(1, min = 13, max = 20)
    }
    x = c(cos(xz*pi/10), sin(xz*pi/10))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.5, 1/3, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.9, 0, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(1/3, .5, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.2, .7, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0.05, 0.05, .9))
      # y = sample(c(1,2,3), size=1,prob= c(1/6, 1/3, .5))
    }
 
    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t = t)
}


plot_ridgeless_circle_boundary <- function(model, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max"){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  if(is.null(ylim)){
    ylim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  
  nd.r1 = seq(from = 0.5, 0.9, length.out = 100)

  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(0.97 * circ.x)
  colnames(circ.nd) <- c("x","y")
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  
  nd1$class <- rep(predict(model, nd.x, rule = rule),100)
 
  
  nd <-  nd1
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(0),cos(6/10*pi),cos(13/10*pi)), y1 = c(0,0,0), y2 = c(sin(0),sin(6/10*pi),sin(13/10*pi)))
  
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .5, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="blue","2"= "green", "3"="red"))
  
  # suppressWarnings(print(plt))
}
##############Three Class################

set.seed(123)
n <- 2000
oracle_data <- generate_noise_circle(10^5)
train_data <- generate_noise_circle(n)
# train_data$oracle_acc
WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

y <- train_data$y
X <- train_data$X
t <- train_data$t
class_idx <- sort(unique(y))
Y <- sapply(class_idx, function(id){as.numeric(y==id)})
m <- length(class_idx)

c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y))



WW_slack <- pmax(1-((cbind(train_data$X,1)%*%t(WW_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(WW_fit$beta)),0)
CS_slack <- pmax(1-((cbind(train_data$X,1)%*%t(CS_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(CS_fit$beta)),0)
Duchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(Duchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(Duchi_fit$beta)),0)
MDuchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(MDuchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(MDuchi_fit$beta)),0)


par(mfrow=c(3,4))
boxplot(WW_slack[y==1,-1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2,-2], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2,-2], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2,-2], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))
boxplot(MDuchi_slack[y==2,-2], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))

boxplot(WW_slack[y==3,-3], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3,-3], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3,-3], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3,-3], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
```



```{r echo=F, fig.width=8, fig.height=2}
g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW")
g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS")
g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi")
g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi")
ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")


```


# Case 1

```{r echo=F, fig.width=8, fig.height=6}
generate_noise_circle <- function(n){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 2)
    }else if(z==2){
      xz <- runif(1, min = 2, max = 11)
    }else if(z==3){
      xz <- runif(1, min = 11, max = 20)
    }
    x = c(cos(xz*pi/10), sin(xz*pi/10))
  
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.5, 1/3, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.9, 0, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(1/3, .5, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.2, .7, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0.05, 0.05, .9))
      # y = sample(c(1,2,3), size=1,prob= c(1/6, 1/3, .5))
    }

    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}

plot_ridgeless_circle_boundary <- function(model, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max"){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  if(is.null(ylim)){
    ylim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  
  nd.r1 = seq(from = 0.5, 0.9, length.out = 100)

  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(0.97 * circ.x)
  colnames(circ.nd) <- c("x","y")
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  
  nd1$class <- rep(predict(model, nd.x, rule = rule),100)
 
  
  nd <-  nd1
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(0),cos(2/10*pi),cos(11/10*pi)), y1 = c(0,0,0), y2 = c(sin(0),sin(2/10*pi),sin(11/10*pi)))
  
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .5, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="blue","2"= "green", "3"="red"))
  
  # suppressWarnings(print(plt))
}


##############Three Class################

set.seed(123)
n <- 2000
oracle_data <- generate_noise_circle(10^5)
train_data <- generate_noise_circle(n)
# train_data$oracle_acc
WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

y <- train_data$y
X <- train_data$X
t <- train_data$t
class_idx <- sort(unique(y))
Y <- sapply(class_idx, function(id){as.numeric(y==id)})
m <- length(class_idx)

c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y))



WW_slack <- pmax(1-((cbind(train_data$X,1)%*%t(WW_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(WW_fit$beta)),0)
CS_slack <- pmax(1-((cbind(train_data$X,1)%*%t(CS_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(CS_fit$beta)),0)
Duchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(Duchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(Duchi_fit$beta)),0)
MDuchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(MDuchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(MDuchi_fit$beta)),0)


par(mfrow=c(3,4))
boxplot(WW_slack[y==1,-1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))


# par(mfrow=c(2,2))
boxplot(WW_slack[y==2,-2], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2,-2], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2,-2], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))
boxplot(MDuchi_slack[y==2,-2], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))

# par(mfrow=c(2,2))
boxplot(WW_slack[y==3,-3], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3,-3], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3,-3], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3,-3], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
```


## sector 1
```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))
boxplot(WW_slack[y==1 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))

boxplot(WW_slack[y==2 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))

```


## sector 2
```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))

boxplot(WW_slack[y==1 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))


```


## sector 3

```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))

boxplot(WW_slack[y==1 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3 & t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3 & t==3]==3),3)), names=c("3vs1", "3vs2"))


```

```{r echo=F, fig.width=8, fig.height=2}
g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW")
g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS")
g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi")
g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi")
ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")

```

# Case 2

```{r echo=F, fig.width=8, fig.height=6}
generate_noise_circle <- function(n){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 5)
    }else if(z==2){
      xz <- runif(1, min = 5, max = 11)
    }else if(z==3){
      xz <- runif(1, min = 11, max = 20)
    }
    x = c(cos(xz*pi/10), sin(xz*pi/10))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.5, 1/3, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.9, 0, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(1/3, .5, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.2, .7, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0.05, 0.05, .9))
      # y = sample(c(1,2,3), size=1,prob= c(1/6, 1/3, .5))
    }

    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}


plot_ridgeless_circle_boundary <- function(model, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max"){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  if(is.null(ylim)){
    ylim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  
  nd.r1 = seq(from = 0.5, 0.9, length.out = 100)

  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(0.97 * circ.x)
  colnames(circ.nd) <- c("x","y")
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  
  nd1$class <- rep(predict(model, nd.x, rule = rule),100)
 
  
  nd <-  nd1
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(0),cos(5/10*pi),cos(11/10*pi)), y1 = c(0,0,0), y2 = c(sin(0),sin(5/10*pi),sin(11/10*pi)))
  
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .5, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="blue","2"= "green", "3"="red"))
  
  # suppressWarnings(print(plt))
}
##############Three Class################

set.seed(123)
n <- 2000
oracle_data <- generate_noise_circle(10^5)
train_data <- generate_noise_circle(n)
# train_data$oracle_acc
WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

y <- train_data$y
X <- train_data$X
t <- train_data$t
class_idx <- sort(unique(y))
Y <- sapply(class_idx, function(id){as.numeric(y==id)})
m <- length(class_idx)

c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y))



WW_slack <- pmax(1-((cbind(train_data$X,1)%*%t(WW_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(WW_fit$beta)),0)
CS_slack <- pmax(1-((cbind(train_data$X,1)%*%t(CS_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(CS_fit$beta)),0)
Duchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(Duchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(Duchi_fit$beta)),0)
MDuchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(MDuchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(MDuchi_fit$beta)),0)



par(mfrow=c(3,4))
boxplot(WW_slack[y==1,-1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2,-2], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2,-2], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2,-2], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))
boxplot(MDuchi_slack[y==2,-2], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))

boxplot(WW_slack[y==3,-3], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3,-3], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3,-3], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3,-3], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
```


## sector 1
```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))
boxplot(WW_slack[y==1 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))

boxplot(WW_slack[y==2 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))

```


## sector 2
```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))

boxplot(WW_slack[y==1 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))


```


## sector 3

```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))

boxplot(WW_slack[y==1 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3 & t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3 & t==3]==3),3)), names=c("3vs1", "3vs2"))


```

```{r echo=F, fig.width=8, fig.height=2}

g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW")
g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS")
g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi")
g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi")
ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")

```



# Case 3

```{r echo=F, fig.width=8, fig.height=6}
generate_noise_circle <- function(n){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 6)
    }else if(z==2){
      xz <- runif(1, min = 6, max = 13)
    }else if(z==3){
      xz <- runif(1, min = 13, max = 20)
    }
    x = c(cos(xz*pi/10), sin(xz*pi/10))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.5, 1/3, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.9, 0, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(1/3, .5, 1/6))
      # y = sample(c(1,2,3), size=1,prob= c(.2, .7, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0.05, 0.05, .9))
      # y = sample(c(1,2,3), size=1,prob= c(1/6, 1/3, .5))
    }
 
    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t = t)
}


plot_ridgeless_circle_boundary <- function(model, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max"){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  if(is.null(ylim)){
    ylim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  
  nd.r1 = seq(from = 0.5, 0.9, length.out = 100)

  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(0.97 * circ.x)
  colnames(circ.nd) <- c("x","y")
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  
  nd1$class <- rep(predict(model, nd.x, rule = rule),100)
 
  
  nd <-  nd1
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(0),cos(6/10*pi),cos(13/10*pi)), y1 = c(0,0,0), y2 = c(sin(0),sin(6/10*pi),sin(13/10*pi)))
  
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .5, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="blue","2"= "green", "3"="red"))
  
  # suppressWarnings(print(plt))
}
##############Three Class################

set.seed(123)
n <- 2000
oracle_data <- generate_noise_circle(10^5)
train_data <- generate_noise_circle(n)
# train_data$oracle_acc
WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

y <- train_data$y
X <- train_data$X
t <- train_data$t
class_idx <- sort(unique(y))
Y <- sapply(class_idx, function(id){as.numeric(y==id)})
m <- length(class_idx)

c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y))



WW_slack <- pmax(1-((cbind(train_data$X,1)%*%t(WW_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(WW_fit$beta)),0)
CS_slack <- pmax(1-((cbind(train_data$X,1)%*%t(CS_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(CS_fit$beta)),0)
Duchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(Duchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(Duchi_fit$beta)),0)
MDuchi_slack <- pmax(1-((cbind(train_data$X,1)%*%t(MDuchi_fit$beta)*Y)%*%matrix(1, nrow = m, ncol = m) - cbind(train_data$X,1)%*%t(MDuchi_fit$beta)),0)


par(mfrow=c(3,4))
boxplot(WW_slack[y==1,-1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2,-2], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2,-2], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2,-2], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))
boxplot(MDuchi_slack[y==2,-2], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2]==2),3)), names=c("2vs1", "2vs1"))

boxplot(WW_slack[y==3,-3], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3,-3], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3,-3], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3,-3], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3]==3),3)), names=c("3vs1", "3vs2"))
```


## sector 1
```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))
boxplot(WW_slack[y==1 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1 & t ==1]==1),3)), names=c("1vs2", "1vs3"))

boxplot(WW_slack[y==2 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==1]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==1, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==1,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==1,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==1,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3& t==1]==3),3)), names=c("3vs1", "3vs2"))

```


## sector 2
```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))

boxplot(WW_slack[y==1 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1& t ==2]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==2]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==2, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==2,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==2,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==2,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3& t==2]==3),3)), names=c("3vs1", "3vs2"))


```


## sector 3

```{r echo=F, fig.width=8, fig.height=6}
par(mfrow=c(3,4))

boxplot(WW_slack[y==1 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(CS_slack[y==1& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(Duchi_slack[y==1& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))
boxplot(MDuchi_slack[y==1& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==1& t ==3]==1),3)), names=c("1vs2", "1vs3"))


boxplot(WW_slack[y==2 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(CS_slack[y==2& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(Duchi_slack[y==2& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))
boxplot(MDuchi_slack[y==2& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==2& t==3]==2),3)), names=c("2vs1", "2vs3"))

boxplot(WW_slack[y==3 & t==3, -1], main = paste("WW",round(mean(predict(WW_fit, oracle_data$X)[oracle_data$y==3& t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(CS_slack[y==3& t==3,-1], main = paste("CS",round(mean(predict(CS_fit, oracle_data$X)[oracle_data$y==3& t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(Duchi_slack[y==3& t==3,-1], main = paste("Duchi", round(mean(predict(Duchi_fit, oracle_data$X)[oracle_data$y==3 & t==3]==3),3)), names=c("3vs1", "3vs2"))
boxplot(MDuchi_slack[y==3& t==3,-1], main = paste("Mduchi", round(mean(predict(MDuchi_fit, oracle_data$X)[oracle_data$y==3 & t==3]==3),3)), names=c("3vs1", "3vs2"))


```

```{r echo=F, fig.width=8, fig.height=2}
g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW")
g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS")
g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi")
g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi")
ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")


```
