---
title: "margin-analysis-VI"
author: "Xinwei"
date: "7/21/2020"
output: 
  html_document:
     toc: true
     toc_depth: 3     
     theme: united
     number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(CVXR)
library(MASS)
library(nnet)
library(parallel)
library(kernlab)
library(ggpubr)
library(ggplot2)
library(glmnet)
set.seed(12)
rm(list = ls())
par(mfrow=c(1,1))
setwd("~/Desktop/Multiclass Classification/MSVM Code")

source("primary form functions.R")


```

# Design 3, Filled Circle, probability1
```{r echo = F}
generate_noise_three_filled_circle <- function(n, sep = 2){
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(0,2) + u/sqrt(sum(u^2)) *sep*cos(1/6*pi) * runif(1,0,1)
    }else if(z==2){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(2*cos(1/6*pi), -2*sin(1/6*pi)) +  u/sqrt(sum(u^2)) *sep*cos(1/6*pi)* runif(1,0,1)
    }else if(z==3){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(-2*cos(1/6*pi), -2*sin(1/6*pi)) +  u/sqrt(sum(u^2)) *sep*cos(1/6*pi)* runif(1,0,1)
    }
    
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.45, .15, .40))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.40, .45, .15))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.15, .40, .45))
    }
    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t = t)
}


plot_batch <- function(train_data){
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  predicted_label <- predict(WW_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("WW:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  predicted_label <- predict(CS_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("CS:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  
                  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  predicted_label <- predict(Duchi_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("Duchi:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  predicted_label <- predict(MDuchi_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("MDuchi:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)
  
  
  
  fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = F)
  Multinom_fit <- MDuchi_fit
  Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
  predicted_label <- predict(Multinom_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("Multinom:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5 <- plot_decision_boundary(Multinom_fit, print = F, title = title)
  
  
  
  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  predicted_label <- predict(New1_fit, train_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == train_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("New1:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g6 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger")
  
  
  
  
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  predicted_label <- predict(New3_fit, train_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == train_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("New3:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g7 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger")

  
    
  MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  predicted_label <- predict(MSVM7_fit, train_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == train_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("MSVM7:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g8 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger")
  
  OVA_fit <- OVA_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  predicted_label <- predict(OVA_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("OVA:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g9 <- plot_decision_boundary(OVA_fit, print = F, title = title)
  
  
  
  MSVM8_fit <- MSVM8_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
  predicted_label <- predict(MSVM8_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("MSVM8:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g10 <- plot_decision_boundary(MSVM8_fit, print = F, title = title)
  

  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
  predicted_label <- predict(WW_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("WW, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g1.1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
  predicted_label <- predict(CS_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("CS, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g2.1 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  
  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
  predicted_label <- predict(Duchi_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("Duchi, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g3.1 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
  predicted_label <- predict(MDuchi_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("MDuchi, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g4.1 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)
  
  
  
  fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = T)
  Multinom_fit <- MDuchi_fit
  Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
  predicted_label <- predict(Multinom_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("Multinom, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g5.1 <- plot_decision_boundary(Multinom_fit, print = F, title = title)
  
  
  New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
  predicted_label <- predict(New1_fit, train_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == train_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("New1, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g6.1 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger")
  
  
  New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
  predicted_label <- predict(New3_fit, train_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == train_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("New3, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g7.1 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger")

  
  MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
  predicted_label <- predict(MSVM7_fit, train_data$X, rule = "dagger") 
  acc <- round(mean(predicted_label == train_data$y, rule = "dagger")*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("MSVM7, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g8.1 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger")

  OVA_fit <- OVA_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
  predicted_label <- predict(OVA_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("OVA:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g9.1 <- plot_decision_boundary(OVA_fit, print = F, title = title)

  
  
  MSVM8_fit <- MSVM8_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
  predicted_label <- predict(MSVM8_fit, train_data$X) 
  acc <- round(mean(predicted_label == train_data$y)*100,2)
  acc_g <- round(c(mean(predicted_label[train_data$t == 1]== train_data$y[train_data$t == 1]), mean(predicted_label[train_data$t == 2]== train_data$y[train_data$t == 2]), mean(predicted_label[train_data$t == 3]== train_data$y[train_data$t == 3]))*100,2)
  title <- paste("MSVM8, intercept:",paste(acc, paste(acc_g, collapse = ","), sep = "\n"))
  g10.1 <- plot_decision_boundary(MSVM8_fit, print = F, title = title)
  
  ggarrange(g1, g2, g3, g4, g5, g6, g7, g8, g9, g10,
            g1.1, g2.1, g3.1, g4.1, g5.1, g6.1, g7.1, g8.1, g9.1, g10.1, ncol=5, nrow=4, common.legend = TRUE, legend="bottom")
  
}



```

## sep = 1.9
```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1.9)
plot_batch(train_data)

```

## sep = 1.5

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1.5)
plot_batch(train_data)

```



## sep = 1

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1)

plot_batch(train_data)




```



## sep = 0.5

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 0.5)
plot_batch(train_data)



```

# Design 3, Filled Circle, probability2

```{r echo = F}


generate_noise_three_filled_circle <- function(n, sep = 2){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(0,2) + u/sqrt(sum(u^2)) *sep*cos(1/6*pi) * runif(1,0,1)
    }else if(z==2){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(2*cos(1/6*pi), -2*sin(1/6*pi)) +  u/sqrt(sum(u^2)) *sep*cos(1/6*pi)* runif(1,0,1)
    }else if(z==3){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(-2*cos(1/6*pi), -2*sin(1/6*pi)) +  u/sqrt(sum(u^2)) *sep*cos(1/6*pi)* runif(1,0,1)
    }
    
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.45, .15, .40))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.30, .55, .15))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.15, .20, .65))
    }
    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t = t)
}
```


## sep = 1.9
```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1.9)

plot_batch(train_data)



```

## sep = 1.5

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1.5)

plot_batch(train_data)


```



## sep = 1

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1)

plot_batch(train_data)


```



## sep = 0.5

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = .5)

plot_batch(train_data)



```


# Design 3, Filled Circle, probability3

```{r echo = F}


generate_noise_three_filled_circle <- function(n, sep = 2){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(0,2) + u/sqrt(sum(u^2)) *sep*cos(1/6*pi) * runif(1,0,1)
    }else if(z==2){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(2*cos(1/6*pi), -2*sin(1/6*pi)) +  u/sqrt(sum(u^2)) *sep*cos(1/6*pi)* runif(1,0,1)
    }else if(z==3){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(-2*cos(1/6*pi), -2*sin(1/6*pi)) +  u/sqrt(sum(u^2)) *sep*cos(1/6*pi)* runif(1,0,1)
    }
    
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.55, .15, .30))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.30, .55, .15))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.15, .30, .55))
    }
    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t = t)
}
```


## sep = 1.9
```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1.9)
plot_batch(train_data)
```

## sep = 1.5

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1.5)
plot_batch(train_data)

```



## sep = 1

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = 1)
plot_batch(train_data)


```



## sep = 0.5

```{r, fig.width=15, fig.height=12, warning=FALSE, echo=F}
n = 3000
train_data <- generate_noise_three_filled_circle(n, sep = .5)

plot_batch(train_data)


```
