---
title: "Margin Analysis II "
author: "Xinwei Zhang"
date: "July 17, 2020"
output: 
  html_document:
     toc: true
     toc_depth: 3   
     theme: united
     number_sections: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(CVXR)
library(MASS)
library(nnet)
library(parallel)
library(kernlab)
library(ggpubr)
library(ggplot2)
library(glmnet)
set.seed(12344)
rm(list = ls())
par(mfrow=c(1,1))
setwd("~/Desktop/Multiclass Classification/MSVM Code")

source("primary form functions.R")


plot_circle_boundary <- function(models, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max", bayes = NULL){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  if(is.null(ylim)){
    ylim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  
  nd.r1 = seq(from = 0.85, 0.9, length.out = 30)
  nd.r2 = seq(from = 0.7, 0.75, length.out = 30)
  nd.r3 = seq(from = 0.55, 0.6, length.out = 30)
  nd.r4 = seq(from = 0.4, 0.45, length.out = 30)
  nd.r5 = seq(from = 0.25, 0.3, length.out = 30)
  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(0.97 * circ.x)
  colnames(circ.nd) <- c("x","y")
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  nd2 = as.data.frame(do.call(rbind,lapply(nd.r2, function(r){r*nd.x})))
  nd3 = as.data.frame(do.call(rbind,lapply(nd.r3, function(r){r*nd.x})))
  nd4 = as.data.frame(do.call(rbind,lapply(nd.r4, function(r){r*nd.x})))
  nd5 = as.data.frame(do.call(rbind,lapply(nd.r5, function(r){r*nd.x})))
  
  nd1$class <- rep(predict(models[[1]], nd.x, rule = rule),30)
  nd2$class <- rep(predict(models[[2]], nd.x, rule = rule),30)
  nd3$class <- rep(predict(models[[3]], nd.x, rule = rule),30)
  nd4$class <- rep(predict(models[[4]], nd.x, rule = rule),30)
  nd5$class <- rep(predict(models[[5]], nd.x, rule = rule),30)
  
  nd <-  rbind(nd1,nd2,nd3,nd4,nd5)
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
  if(is.null(bayes) == T){
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(1.5/10.5*pi), cos(8.5/10.5*pi),cos(15.5/10.5*pi)), y1 = c(0,0,0), y2 = c(sin(1.5/10.5*pi),sin(8.5/10.5*pi),sin(15.5/10.5*pi)))
  }else{
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = sapply(bayes, function(t){cos(t*pi/10.5)}), y1 = c(0,0,0), y2 = sapply(bayes, function(t){sin(t*pi/10.5)}))
  }
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .5, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="red","2"= "green", "3"="blue"))
  
}

plot_ridgeless_circle_boundary <- function(model, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max", bayes = NULL){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  if(is.null(ylim)){
    ylim = c( floor(min(X_dat$x,X_dat$y))-.1, ceiling(max(X_dat$x,X_dat$y))+.1)
  }
  
  nd.r1 = seq(from = 0.5, 0.9, length.out = 100)

  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(0.97 * circ.x)
  colnames(circ.nd) <- c("x","y")
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  
  nd1$class <- rep(predict(model, nd.x, rule = rule),100)
 
  
  nd <-  nd1
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
  seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(1.5/10.5*pi), cos(8.5/10.5*pi),cos(15.5/10.5*pi)), y1 = c(0,0,0), y2 = c(sin(1.5/10.5*pi),sin(8.5/10.5*pi),sin(15.5/10.5*pi)))
  if(is.null(bayes) == T){
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(cos(1.5/10.5*pi), cos(8.5/10.5*pi),cos(15.5/10.5*pi)), y1 = c(0,0,0), y2 = c(sin(1.5/10.5*pi),sin(8.5/10.5*pi),sin(15.5/10.5*pi)))
  }else{
    seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = sapply(bayes, function(t){cos(t*pi/10.5)}), y1 = c(0,0,0), y2 = sapply(bayes, function(t){sin(t*pi/10.5)}))
  }
  
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .5, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="red","2"= "green", "3"="blue"))
  
  # suppressWarnings(print(plt))
}



generate_noise_circle <- function(n, bayes){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = bayes[1])
    }else if(z==2){
      xz <- runif(1, min = 7, max = bayes[2])
    }else if(z==3){
      xz <- runif(1, min = 14, max = bayes[3])
    }
    x = c(cos(xz*pi/10.5), sin(xz*pi/10.5))
  
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.15, .45, .4))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.4, .15, .45))
    }

    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}

plot_gamma <- function(fit){
  z <- seq(0,2*pi, length.out = 2000)
  X <- cbind(cos(z), sin(z),1)
  p_dat <- as.data.frame(cbind(z,X%*%t(fit$beta)))
  colnames(p_dat) <- c("theta", "gamma1", "gamma2", "gamma3")
  g <- ggplot(p_dat, aes(x=theta)) + 
  geom_line(aes(y = gamma1), color = "red") + 
  geom_line(aes(y = gamma2), color="green") +
  geom_line(aes(y = gamma3), color="blue") +
  geom_hline(yintercept = 1/3, linetype = "dashed")
  return(g)
}

plot_batch <- function(data_bayes, plot_bayes){
  
  n <- 2000
  oracle_data <- generate_noise_circle(10^5, data_bayes)
  train_data <- generate_noise_circle(n, data_bayes)
  
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  
  y <- train_data$y
  X <- train_data$X
  t <- train_data$t
  class_idx <- sort(unique(y))
  Y <- sapply(class_idx, function(id){as.numeric(y==id)})
  m <- length(class_idx)
  
  print(c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
  mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
  mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
  mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y)))
  
  
  g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW", bayes = plot_bayes)
  g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS", bayes = plot_bayes)
  g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi", bayes = plot_bayes)
  g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi", bayes = plot_bayes)
  # ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")
  
  C_list <- 10^seq(0,-4,length.out = 5)
    
  g1.1 <- plot_circle_boundary(lapply(C_list, function(C){WW_pri_opt(X,y,C,intercept = F)}), X, y, title = "WW", bayes = plot_bayes)
  g2.1 <- plot_circle_boundary(lapply(C_list, function(C){CS_pri_opt(X,y,C,intercept = F)}), X, y, title = "CS", bayes = plot_bayes)
  g3.1 <- plot_circle_boundary(lapply(C_list, function(C){Duchi_pri_opt(X,y,C,intercept = F)}), X, y, title = "Duchi", bayes = plot_bayes)
  g4.1 <- plot_circle_boundary(lapply(C_list, function(C){MDuchi_pri_opt(X,y,C,intercept = F)}), X, y, title = "MDuchi", bayes = plot_bayes)
  

  g1.2 <- plot_gamma(WW_fit)
  g2.2 <- plot_gamma(CS_fit)
  g3.2 <- plot_gamma(Duchi_fit)
  g4.2 <- plot_gamma(MDuchi_fit)
  
  ggarrange(g1, g2, g3, g4, g1.1, g2.1, g3.1, g4.1, g1.2, g2.2, g3.2, g4.2, ncol=4, nrow=3, common.legend = TRUE, legend="bottom")
    
}
```
# Design 1
## Probability 1
### Case 1

```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(1, 8, 15)
plot_bayes <- c(.5, 7.5, 14.5)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 2
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(2, 9, 16)
plot_bayes <- c(1, 8, 15)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 3
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(3, 10, 17)
plot_bayes <- c(1.5, 8.5, 15.5)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 4

```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(4, 11, 18)
plot_bayes <- c(2, 9, 16)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 5
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(5, 12, 19)
plot_bayes <- c(2.5, 9.5, 16.5)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 6
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(6, 13, 20)
plot_bayes <- c(3, 10, 17)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 7
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(7, 14, 21)
plot_bayes <- c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


## Probability 2
```{r echo = F}
generate_noise_circle <- function(n, bayes){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = bayes[1])
    }else if(z==2){
      xz <- runif(1, min = 7, max = bayes[2])
    }else if(z==3){
      xz <- runif(1, min = 14, max = bayes[3])
    }
    x = c(cos(xz*pi/10.5), sin(xz*pi/10.5))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    }

    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}


plot_batch <- function(data_bayes, plot_bayes){

  n <- 2000
  oracle_data <- generate_noise_circle(10^5, data_bayes)
  train_data <- generate_noise_circle(n, data_bayes)

  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

  y <- train_data$y
  X <- train_data$X
  t <- train_data$t
  class_idx <- sort(unique(y))
  Y <- sapply(class_idx, function(id){as.numeric(y==id)})
  m <- length(class_idx)

  print(c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
  mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
  mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
  mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y)))


  g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW", bayes = plot_bayes)
  g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS", bayes = plot_bayes)
  g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi", bayes = plot_bayes)
  g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi", bayes = plot_bayes)
  # ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")

  C_list <- 10^seq(0,-4,length.out = 5)

  g1.1 <- plot_circle_boundary(lapply(C_list, function(C){WW_pri_opt(X,y,C,intercept = F)}), X, y, title = "WW", bayes = plot_bayes)
  g2.1 <- plot_circle_boundary(lapply(C_list, function(C){CS_pri_opt(X,y,C,intercept = F)}), X, y, title = "CS", bayes = plot_bayes)
  g3.1 <- plot_circle_boundary(lapply(C_list, function(C){Duchi_pri_opt(X,y,C,intercept = F)}), X, y, title = "Duchi", bayes = plot_bayes)
  g4.1 <- plot_circle_boundary(lapply(C_list, function(C){MDuchi_pri_opt(X,y,C,intercept = F)}), X, y, title = "MDuchi", bayes = plot_bayes)


  g1.2 <- plot_gamma(WW_fit)
  g2.2 <- plot_gamma(CS_fit)
  g3.2 <- plot_gamma(Duchi_fit)
  g4.2 <- plot_gamma(MDuchi_fit)

  ggarrange(g1, g2, g3, g4, g1.1, g2.1, g3.1, g4.1, g1.2, g2.2, g3.2, g4.2, ncol=4, nrow=3, common.legend = TRUE, legend="bottom")

}
```
### Case 1

```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(1, 8, 15)
plot_bayes <- c(.5, 7.5, 14.5)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 2
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(2, 9, 16)
plot_bayes <- c(1, 8, 15)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 3
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(3, 10, 17)
plot_bayes <- c(1.5, 8.5, 15.5)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 4

```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(4, 11, 18)
plot_bayes <- c(2, 9, 16)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 5
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(5, 12, 19)
plot_bayes <- c(2.5, 9.5, 16.5)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 6
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(6, 13, 20)
plot_bayes <- c(3, 10, 17)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 7
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(7, 14, 21)
plot_bayes <- c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```




## Probability 3

```{r echo = F}
generate_noise_circle <- function(n, bayes){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = bayes[1])
    }else if(z==2){
      xz <- runif(1, min = 7, max = bayes[2])
    }else if(z==3){
      xz <- runif(1, min = 14, max = bayes[3])
    }
    x = c(cos(xz*pi/10.5), sin(xz*pi/10.5))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }

    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}


plot_batch <- function(data_bayes, plot_bayes){

  n <- 2000
  oracle_data <- generate_noise_circle(10^5, data_bayes)
  train_data <- generate_noise_circle(n, data_bayes)

  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

  y <- train_data$y
  X <- train_data$X
  t <- train_data$t
  class_idx <- sort(unique(y))
  Y <- sapply(class_idx, function(id){as.numeric(y==id)})
  m <- length(class_idx)

  print(c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
  mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
  mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
  mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y)))


  g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW", bayes = plot_bayes)
  g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS", bayes = plot_bayes)
  g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi", bayes = plot_bayes)
  g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi", bayes = plot_bayes)
  # ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")

  C_list <- 10^seq(0,-4,length.out = 5)

  g1.1 <- plot_circle_boundary(lapply(C_list, function(C){WW_pri_opt(X,y,C,intercept = F)}), X, y, title = "WW", bayes = plot_bayes)
  g2.1 <- plot_circle_boundary(lapply(C_list, function(C){CS_pri_opt(X,y,C,intercept = F)}), X, y, title = "CS", bayes = plot_bayes)
  g3.1 <- plot_circle_boundary(lapply(C_list, function(C){Duchi_pri_opt(X,y,C,intercept = F)}), X, y, title = "Duchi", bayes = plot_bayes)
  g4.1 <- plot_circle_boundary(lapply(C_list, function(C){MDuchi_pri_opt(X,y,C,intercept = F)}), X, y, title = "MDuchi", bayes = plot_bayes)


  g1.2 <- plot_gamma(WW_fit)
  g2.2 <- plot_gamma(CS_fit)
  g3.2 <- plot_gamma(Duchi_fit)
  g4.2 <- plot_gamma(MDuchi_fit)

  ggarrange(g1, g2, g3, g4, g1.1, g2.1, g3.1, g4.1, g1.2, g2.2, g3.2, g4.2, ncol=4, nrow=3, common.legend = TRUE, legend="bottom")

}
```
### Case 1

```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(1, 14, 21)
plot_bayes <- c(.5, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)
```

### Case 2
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(2, 14, 21)
plot_bayes <- c(1, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)
```


### Case 3
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(3, 14, 21)
plot_bayes <- c(1.5, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)
```


### Case 4

```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(4, 14, 21)
plot_bayes <- c(2, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)
```

### Case 5
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(5, 14, 21)
plot_bayes <- c(2.5, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)
```

### Case 6
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(6, 14, 21)
plot_bayes <- c(3, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)
```


### Case 7
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(7, 14, 21)
plot_bayes <- c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)
```



## Probability 4


```{r echo = F}
generate_noise_circle <- function(n, bayes){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = bayes[1])
    }else if(z==2){
      xz <- runif(1, min = 7, max = bayes[2])
    }else if(z==3){
      xz <- runif(1, min = 14, max = bayes[3])
    }
    x = c(cos(xz*pi/10.5), sin(xz*pi/10.5))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.7, .2, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.1, .7, .2))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.2, .1, .7))
    }

    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y), t=t)
}


plot_batch <- function(data_bayes, plot_bayes){

  n <- 2000
  oracle_data <- generate_noise_circle(10^5, data_bayes)
  train_data <- generate_noise_circle(n, data_bayes)

  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)

  y <- train_data$y
  X <- train_data$X
  t <- train_data$t
  class_idx <- sort(unique(y))
  Y <- sapply(class_idx, function(id){as.numeric(y==id)})
  m <- length(class_idx)

  print(c(mean(predict(WW_fit, oracle_data$X) == oracle_data$y),
  mean(predict(CS_fit, oracle_data$X) == oracle_data$y),
  mean(predict(Duchi_fit, oracle_data$X) == oracle_data$y),
  mean(predict(MDuchi_fit, oracle_data$X) == oracle_data$y)))


  g1 <- plot_ridgeless_circle_boundary(WW_fit, X, y, title = "WW", bayes = plot_bayes)
  g2 <- plot_ridgeless_circle_boundary(CS_fit, X, y, title = "CS", bayes = plot_bayes)
  g3 <- plot_ridgeless_circle_boundary(Duchi_fit, X, y, title = "Duchi", bayes = plot_bayes)
  g4 <- plot_ridgeless_circle_boundary(MDuchi_fit, X, y, title = "Mduchi", bayes = plot_bayes)
  # ggarrange(g1, g2, g3,g4, ncol=4, nrow=1, common.legend = TRUE, legend="bottom")

  C_list <- 10^seq(0,-4,length.out = 5)

  g1.1 <- plot_circle_boundary(lapply(C_list, function(C){WW_pri_opt(X,y,C,intercept = F)}), X, y, title = "WW", bayes = plot_bayes)
  g2.1 <- plot_circle_boundary(lapply(C_list, function(C){CS_pri_opt(X,y,C,intercept = F)}), X, y, title = "CS", bayes = plot_bayes)
  g3.1 <- plot_circle_boundary(lapply(C_list, function(C){Duchi_pri_opt(X,y,C,intercept = F)}), X, y, title = "Duchi", bayes = plot_bayes)
  g4.1 <- plot_circle_boundary(lapply(C_list, function(C){MDuchi_pri_opt(X,y,C,intercept = F)}), X, y, title = "MDuchi", bayes = plot_bayes)


  g1.2 <- plot_gamma(WW_fit)
  g2.2 <- plot_gamma(CS_fit)
  g3.2 <- plot_gamma(Duchi_fit)
  g4.2 <- plot_gamma(MDuchi_fit)

  ggarrange(g1, g2, g3, g4, g1.1, g2.1, g3.1, g4.1, g1.2, g2.2, g3.2, g4.2, ncol=4, nrow=3, common.legend = TRUE, legend="bottom")

}
```
### Case 1

```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(1, 8, 15)
plot_bayes <-  c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 2
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(2, 9, 16)
plot_bayes <-  c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 3
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(3, 10, 17)
plot_bayes <-  c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 4

```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(4, 11, 18)
plot_bayes <-  c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 5
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(5, 12, 19)
plot_bayes <-  c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```

### Case 6
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(6, 13, 20)
plot_bayes <-  c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)

```


### Case 7
```{r echo=F, fig.width=12, fig.height=9}
data_bayes <- c(7, 14, 21)
plot_bayes <- c(7, 14, 21)
plot_batch(data_bayes = data_bayes, plot_bayes = plot_bayes)
```



# Design 2
## sep = 1.9
```{r, fig.width=15, fig.height=9, warning=FALSE, echo=F}


generate_noise_three_circle <- function(n, sep = 2){
  
  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(0,2) + u/sqrt(sum(u^2)) *sep*cos(1/6*pi)
    }else if(z==2){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(2*cos(1/6*pi), -2*sin(1/6*pi)) +  u/sqrt(sum(u^2)) *sep*cos(1/6*pi)
    }else if(z==3){
      u <- mvrnorm(1,c(0,0),diag(1,2))
      x <- c(-2*cos(1/6*pi), -2*sin(1/6*pi)) +  u/sqrt(sum(u^2)) *sep*cos(1/6*pi)
    }
    

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.45, .15, .40))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.40, .45, .15))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.15, .40, .45))
    }
    return(c(x,y))
  }))
  X <- dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y, oracle_acc = mean(t==y))
}

n = 3000
train_data <- generate_noise_three_circle(n, sep =1.9)

WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
g1 <- plot_decision_boundary(WW_fit, print = F, title = "WW")

CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
g2 <- plot_decision_boundary(CS_fit, print = F, title = "CS")

Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
g3 <- plot_decision_boundary(Duchi_fit, print = F, title = "Duchi")

MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
g4 <- plot_decision_boundary(MDuchi_fit, print = F, title = "MDuchi")

fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = F)
w <- cbind(t(do.call(cbind,coef(fit)))[,c(2,3)],0)
Multinom_fit <- MDuchi_fit
Multinom_fit$beta <- w
g5 <- plot_decision_boundary(Multinom_fit, print = F, title = "Multinom")



WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
g6 <- plot_decision_boundary(WW_fit, print = F, title = "WW")

CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
g7 <- plot_decision_boundary(CS_fit, print = F, title = "CS")

Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
g8 <- plot_decision_boundary(Duchi_fit, print = F, title = "Duchi")

MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
g9 <- plot_decision_boundary(MDuchi_fit, print = F, title = "MDuchi")

fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = T)

Multinom_fit <- MDuchi_fit
Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
g10 <- plot_decision_boundary(Multinom_fit, print = F, title = "Multinom")


ggarrange(g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, ncol=5, nrow=2, common.legend = TRUE, legend="bottom")

```

## sep = 1.5
```{r, fig.width=15, fig.height=9, warning=FALSE, echo=F}

n = 3000
train_data <- generate_noise_three_circle(n, sep = 1.5)


WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
g1 <- plot_decision_boundary(WW_fit, print = F, title = "WW")

CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
g2 <- plot_decision_boundary(CS_fit, print = F, title = "CS")

Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
g3 <- plot_decision_boundary(Duchi_fit, print = F, title = "Duchi")

MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
g4 <- plot_decision_boundary(MDuchi_fit, print = F, title = "MDuchi")

fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = F)
w <- cbind(t(do.call(cbind,coef(fit)))[,c(2,3)],0)
Multinom_fit <- MDuchi_fit
Multinom_fit$beta <- w
g5 <- plot_decision_boundary(Multinom_fit, print = F, title = "Multinom")



WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
g6 <- plot_decision_boundary(WW_fit, print = F, title = "WW")

CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
g7 <- plot_decision_boundary(CS_fit, print = F, title = "CS")

Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
g8 <- plot_decision_boundary(Duchi_fit, print = F, title = "Duchi")

MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
g9 <- plot_decision_boundary(MDuchi_fit, print = F, title = "MDuchi")

fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = T)

Multinom_fit <- MDuchi_fit
Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
g10 <- plot_decision_boundary(Multinom_fit, print = F, title = "Multinom")


ggarrange(g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, ncol=5, nrow=2, common.legend = TRUE, legend="bottom")

```


## sep = 1
```{r, fig.width=15, fig.height=9, warning=FALSE, echo=F}

n = 3000
train_data <- generate_noise_three_circle(n, sep = 1)


WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
g1 <- plot_decision_boundary(WW_fit, print = F, title = "WW")

CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
g2 <- plot_decision_boundary(CS_fit, print = F, title = "CS")

Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
g3 <- plot_decision_boundary(Duchi_fit, print = F, title = "Duchi")

MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
g4 <- plot_decision_boundary(MDuchi_fit, print = F, title = "MDuchi")

fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = F)
w <- cbind(t(do.call(cbind,coef(fit)))[,c(2,3)],0)
Multinom_fit <- MDuchi_fit
Multinom_fit$beta <- w
g5 <- plot_decision_boundary(Multinom_fit, print = F, title = "Multinom")



WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
g6 <- plot_decision_boundary(WW_fit, print = F, title = "WW")

CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
g7 <- plot_decision_boundary(CS_fit, print = F, title = "CS")

Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
g8 <- plot_decision_boundary(Duchi_fit, print = F, title = "Duchi")

MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
g9 <- plot_decision_boundary(MDuchi_fit, print = F, title = "MDuchi")

fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = T)

Multinom_fit <- MDuchi_fit
Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
g10 <- plot_decision_boundary(Multinom_fit, print = F, title = "Multinom")


ggarrange(g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, ncol=5, nrow=2, common.legend = TRUE, legend="bottom")

```


## sep = .5
```{r, fig.width=15, fig.height=9, warning=FALSE, echo=F}

n = 3000
train_data <- generate_noise_three_circle(n, sep =.5)


WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
g1 <- plot_decision_boundary(WW_fit, print = F, title = "WW")

CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
g2 <- plot_decision_boundary(CS_fit, print = F, title = "CS")

Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = F)
g3 <- plot_decision_boundary(Duchi_fit, print = F, title = "Duchi")

MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = F)
g4 <- plot_decision_boundary(MDuchi_fit, print = F, title = "MDuchi")

fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = F)
w <- cbind(t(do.call(cbind,coef(fit)))[,c(2,3)],0)
Multinom_fit <- MDuchi_fit
Multinom_fit$beta <- w
g5 <- plot_decision_boundary(Multinom_fit, print = F, title = "Multinom")



WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
g6 <- plot_decision_boundary(WW_fit, print = F, title = "WW")

CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
g7 <- plot_decision_boundary(CS_fit, print = F, title = "CS")

Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C=1, lambda=0, intercept = T)
g8 <- plot_decision_boundary(Duchi_fit, print = F, title = "Duchi")

MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y, C=1, lambda=0, intercept = T)
g9 <- plot_decision_boundary(MDuchi_fit, print = F, title = "MDuchi")

fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = T)

Multinom_fit <- MDuchi_fit
Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
g10 <- plot_decision_boundary(Multinom_fit, print = F, title = "Multinom")


ggarrange(g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, ncol=5, nrow=2, common.legend = TRUE, legend="bottom")

```