---
title: "New Experiment from Ben-David 3-class"
author: "Xinwei"
date: "8/20/2020"
output:
  html_document:
       toc: true
       toc_depth: 3   
       theme: united
       number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
library(CVXR)
library(MASS)
library(R.matlab)
library(e1071)
library(kernlab)
library(ggpubr)
library(glmnet)
library(truncnorm)
library(ggplot2)
rm(list=ls())
setwd("~/Desktop/Multiclass Classification/MSVM Code")
source("primary form functions.R")

source("kernel primary form functions.R")

plot_batch <- function(train_data, test_data, C, lambda, intercept = T, sep){
    
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(WW_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("WW:",acc)
  g1.1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(CS_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("CS:",acc)
  g1.2 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C= 1, lambda=0, intercept = intercept)
  predicted_label <- predict(Duchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Duchi:",acc)
  g1.3 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MDuchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MDuchi:",acc)
  g1.4 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)
  

# 
#   
#   New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
#   predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("New1:",acc)
#   g2.1 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
#   
#     
#   New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
#   predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("New1:",acc)
#   g2.2 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
#   
#   New1_fit <- New1_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
#   predicted_label <- predict(New1_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("New1:",acc)
#   g2.3 <- plot_decision_boundary(New1_fit, print = F, title = title, rule = "dagger") 
#   
#   
# 
# 
# 
#   New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
#   predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("New3:",acc)
#   g3.1 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
#  
#   New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
#   predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("New3:",acc)
#   g3.2 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
#   
#   New3_fit <- New3_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
#   predicted_label <- predict(New3_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("New3:",acc)
#   g3.3 <- plot_decision_boundary(New3_fit, print = F, title = title, rule = "dagger") 
#   
#   # 
#   g4.1 <- tryCatch({
#   LLW_fit <- LLW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
#   predicted_label <- predict(LLW_fit, test_data$X)
#   acc <- round(mean(predicted_label == test_data$y)*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("MSVM7:",acc)
#   return(plot_decision_boundary(LLW_fit, print = F, title = title, rule = "dagger"))
#   }, error = function(e){ NULL})
#   
#   OVA_fit <- OVA_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
#   predicted_label <- predict(OVA_fit, test_data$X) 
#   acc <- round(mean(predicted_label == test_data$y)*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("OVA:",acc)
#   g4.2 <- plot_decision_boundary(OVA_fit, print = F, title = title)
#   
#   
#   
#   
#   MSVM8_fit <- MSVM8_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
#   predicted_label <- predict(MSVM8_fit, test_data$X) 
#   acc <- round(mean(predicted_label == test_data$y)*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("MSVM8:",acc)
#   g4.3 <- plot_decision_boundary(MSVM8_fit, print = F, title = title)
#   
#   fit <- glmnet(x =  train_data$X, y =  train_data$y, family = "multinomial", lambda=0, intercept = intercept)
#   Multinom_fit <- MDuchi_fit
#   Multinom_fit$beta <- t(do.call(cbind,coef(fit)))[,c(2,3,1)]
#   predicted_label <- predict(Multinom_fit, test_data$X)
#   acc <- round(mean(predicted_label == test_data$y)*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("Multinom:",acc)
#   g4.4 <- plot_decision_boundary(Multinom_fit, print = F, title = title)
# 
#   
#   MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 1)
#   predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("MSVM7:",acc)
#   g5.1 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
#   
#    MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 2)
#   predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("MSVM7:",acc)
#   g5.2 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
#   
#    MSVM7_fit <- MSVM7_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept, base_class = 3)
#   predicted_label <- predict(MSVM7_fit, test_data$X, rule = "dagger") 
#   acc <- round(mean(predicted_label == test_data$y, rule = "dagger")*100,2)
#   # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
#   title <- paste("MSVM7:",acc)
#   g5.3 <- plot_decision_boundary(MSVM7_fit, print = F, title = title, rule = "dagger") 
#         
  
  # ggarrange(g1.1, g1.2, g1.3, g1.4,
  #           g2.1, g2.2, g2.3, NULL,
  #           g3.1, g3.2, g3.3, NULL,
  #           g4.1, g4.2, g4.3, g4.4,
  #           g5.1, g5.2, g5.3, NULL, ncol=4, nrow = 5, common.legend = TRUE, legend="bottom")
  # 
  figure <- ggarrange(g1.1, g1.2, g1.3, g1.4,
            ncol=4, nrow = 1, common.legend = TRUE, legend="bottom")
  


  print(annotate_figure(figure,
               top = text_grob(paste("Sep=",sep,sep=""), color = "red", face = "bold", size = 14)
  ))

}


```


#Case 1

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
  Sigma <- (diag(1,nrow=2)/10)^2
  t <- c(rep(seq(1,3), round(n*.9/3)), rep(4, round(n*.1))) 
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- mvrnorm(1, c(0,2), Sigma)
    }else if(z==2){
      xz <- mvrnorm(1, c(0,0), Sigma)
    }else if(z==3){
      xz <- mvrnorm(1, c(2,0), Sigma)
    }else if(z==4){
      xz <-  mvrnorm(1, c(0,-sep), Sigma)
    }
 
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- dat[,1:2]
  y <- dat[,3]
  
  list(X=X,y=y)
}

n_train <- 2500
n_test <- 100000

```

## intercept = T

```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(1.5,5,by=.25), function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```


```{r fig.width = 12, fig.height= 3, echo = F}

generate_data <- function(n, sep){
  Sigma <- (diag(1,nrow=2)/10)^2
  t <- c(rep(seq(1,3), round(n*.9/3)), rep(4, round(n*.1))) 
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,2), Sigma)
      
      xz <- c(0,2)
    }else if(z==2){
      xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(0,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(2,0), Sigma)
      xz <- c(2,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-sep), Sigma)
      xz <- c(0,-sep)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- dat[,1:2]
  y <- dat[,3]
  
  list(X=X,y=y)
}

n_train <- 2500
n_test <- 100000

```

# Case 2
## intercept = T

```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(1.5,5,by=.25), function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```

# Case 3
## intercept = T

```{r}
generate_data <- function(n, sep){
  Sigma <- (diag(1,nrow=2)/20)^2
  # t <- sample(c(1,2,3,4), size = n, replace = T, prob = c(.3,.3,.3,.1))
   t <- c(rep(seq(1,3), round(n*.9/3)), rep(4, round(n*.1))) 
  
  dat <- t(sapply(t, function(z){
     if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(0,8)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(0,4)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(0,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(0, -sep)
    }
 
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))

  X <- dat[,1:2]
  y <- dat[,3]

  list(X=X,y=y)
}

n_train <- 2500
n_test <- 100000

```

```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(1,5,by=.5), function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```
