---
title: "New2-Experiment-from-Ben-David-0910"
author: "Xinwei"
date: "9/10/2020"
output:
  html_document:
    toc: true
    toc_depth: 3   
    theme: united
    number_sections: true
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
library(CVXR)
library(MASS)
library(R.matlab)
library(e1071)
library(kernlab)
library(ggpubr)
library(glmnet)
library(truncnorm)
library(ggplot2)
rm(list=ls())
setwd("~/Desktop/Multiclass Classification/MSVM Code")
source("primary form functions.R")

plot_batch <- function(train_data, test_data, C, lambda, intercept = T, sep){
  
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(WW_fit, test_data$X) 
  acc <- round(100 - mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("ERR of WW:",acc)
  g1.1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(CS_fit, test_data$X) 
  acc <- round(100 - mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("ERR of CS:",acc)
  g1.2 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C= 1, lambda=0, intercept = intercept)
  predicted_label <- predict(Duchi_fit, test_data$X) 
  acc <- round(100 - mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("ERR of Duchi:",acc)
  g1.3 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MDuchi_fit, test_data$X) 
  acc <- round(100 - mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("ERR of MDuchi:",acc)
  g1.4 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)

  figure <- ggarrange(g1.1, g1.2, g1.3, g1.4,
                      ncol=4, nrow = 1, common.legend = TRUE, legend="bottom")
  
  
  print(annotate_figure(figure,
                        top = text_grob(paste("Sep=",sep,sep=""), color = "red", face = "bold", size = 14)
  ))
  
}


```
# 1
## Case 1
### Case 1, Prob = 0

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
   t <- c(rep(1, round(n*(1-8/5*0.18 -8/5*0.18 - 0.18))), rep(2, round(n*8/5*0.18)),rep(3, round(n*8/5*0.18)), rep(4, round(n*0.18)))
  
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(-1+sep,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(-1+2*sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  
  list(X=X,y=y)
}

n_train <- 2000
n_test <- 100000

```


```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```

### Case 1, Prob = 1

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
   t <- c(rep(1, round(n*(1-8/5*0.15 -8/5*0.15 - 0.15))), rep(2, round(n*8/5*0.15)),rep(3, round(n*8/5*0.15)), rep(4, round(n*0.15)))
   
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(-1+sep,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(-1+2*sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  
  list(X=X,y=y)
}

n_train <- 2000
n_test <- 100000

```


```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```

### Case 1, Prob = 2

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
  
  t <- c(rep(1, round(n*(1-8/5*0.1 -8/5*0.1 - 0.1))), rep(2, round(n*8/5*0.1)),rep(3, round(n*8/5*0.1)), rep(4, round(n*0.1)))
   
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(-1+sep,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(-1+2*sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  list(X=X,y=y)
}

n_train <- 2000
n_test <- 100000

```


```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```


### Case 1, Prob = 3

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
  
  t <- c(rep(1, round(n*(1-8/5*0.05 -8/5*0.05 - 0.05))), rep(2, round(n*8/5*0.05)),rep(3, round(n*8/5*0.05)), rep(4, round(n*0.05)))
  
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(-1+sep,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(-1+2*sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  list(X=X,y=y)
}

n_train <- 2000
n_test <- 100000

```


```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```



### Case 1, Prob = 4

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
  
  t <- c(rep(1, round(n*(1-8/5*0.02 -8/5*0.02 - 0.02))), rep(2, round(n*8/5*0.02)),rep(3, round(n*8/5*0.02)), rep(4, round(n*0.02)))
  
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(-1+sep,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(-1+2*sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  list(X=X,y=y)
}

n_train <- 2500
n_test <- 100000

```

```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```











```{r echo = F}
plot_batch <- function(train_data, test_data, C, lambda, intercept = T, sep){
  
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(WW_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("WW:",acc)
  g1.1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(CS_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("CS:",acc)
  g1.2 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C= 1, lambda=lambda, intercept = intercept)
  predicted_label <- predict(Duchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Duchi:",acc)
  g1.3 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MDuchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MDuchi:",acc)
  g1.4 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)

  figure <- ggarrange(g1.1, g1.2, g1.3, g1.4,
                      ncol=4, nrow = 1, common.legend = TRUE, legend="bottom")
    
  
  print(annotate_figure(figure,
                        top = text_grob(paste("Sep=",sep,sep=""), color = "red", face = "bold", size = 14)
  ))
  
}


```


## Case 2
### Case 2, Prob = 0

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
   t <- c(rep(1, round(n*(1-8/5*0.18 -8/5*0.18 - 0.18))), rep(2, round(n*8/5*0.18)),rep(3, round(n*8/5*0.18)), rep(4, round(n*0.18)))
  
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(0,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  
  list(X=X,y=y)
}

n_train <- 2000
n_test <- 100000

```


```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```

### Case 1, Prob = 1

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
   t <- c(rep(1, round(n*(1-8/5*0.15 -8/5*0.15 - 0.15))), rep(2, round(n*8/5*0.15)),rep(3, round(n*8/5*0.15)), rep(4, round(n*0.15)))
   
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(0,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  
  list(X=X,y=y)
}

n_train <- 2000
n_test <- 100000

```


```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```

### Case 1, Prob = 2

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
  
  t <- c(rep(1, round(n*(1-8/5*0.1 -8/5*0.1 - 0.1))), rep(2, round(n*8/5*0.1)),rep(3, round(n*8/5*0.1)), rep(4, round(n*0.1)))
   
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(0,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  list(X=X,y=y)
}

n_train <- 2000
n_test <- 100000

```


```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```


### Case 1, Prob = 3

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
  
  t <- c(rep(1, round(n*(1-8/5*0.05 -8/5*0.05 - 0.05))), rep(2, round(n*8/5*0.05)),rep(3, round(n*8/5*0.05)), rep(4, round(n*0.05)))
  
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(0,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  list(X=X,y=y)
}

n_train <- 2000
n_test <- 100000

```


```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```



### Case 1, Prob = 4

```{r fig.width = 12, fig.height= 3, echo = F}
generate_data <- function(n, sep){
  
  t <- c(rep(1, round(n*(1-8/5*0.02 -8/5*0.02 - 0.02))), rep(2, round(n*8/5*0.02)),rep(3, round(n*8/5*0.02)), rep(4, round(n*0.02)))
  
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- mvrnorm(1, c(0,8), Sigma)
      xz <- c(-1,0)
    }else if(z==2){
      # xz <- mvrnorm(1, c(0,4), Sigma)
      xz <- c(0,0)
    }else if(z==3){
      # xz <- mvrnorm(1, c(0,0), Sigma)
      xz <- c(sep,0)
    }else if(z==4){
      # xz <-  mvrnorm(1, c(0,-2), Sigma)
      xz <- c(1,0)
    }
    
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(0, 1, 0))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(0, 0, 1))
    }else if(z==4){
      y = sample(c(1,2,3), size=1,prob= c(1, 0, 0))
    }
    return(c(xz,y))
  }))
  
  X <- as.matrix(dat[,c(1,2)])
  y <- dat[,3]
  
  list(X=X,y=y)
}

n_train <- 2500
n_test <- 100000

```

```{r fig.width = 12, fig.height= 3, echo = F}
res <- sapply(seq(from = 10, to = 1)/10, function(sep){
  train_data <- generate_data(n_train, sep)
  test_data <- generate_data(n_test, sep)
  plot_batch(train_data, test_data,  C=1, lambda = 0, intercept = T, sep = sep)
})
```











```{r echo = F}
plot_batch <- function(train_data, test_data, C, lambda, intercept = T, sep){
  
  WW_fit <- WW_pri_opt(train_data$X,train_data$y, C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(WW_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("WW:",acc)
  g1.1 <- plot_decision_boundary(WW_fit, print = F, title = title)
  
  CS_fit <- CS_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(CS_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("CS:",acc)
  g1.2 <- plot_decision_boundary(CS_fit, print = F, title = title)
  
  Duchi_fit <- Duchi_pri_opt(train_data$X,train_data$y,  C= 1, lambda=lambda, intercept = intercept)
  predicted_label <- predict(Duchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("Duchi:",acc)
  g1.3 <- plot_decision_boundary(Duchi_fit, print = F, title = title)
  
  MDuchi_fit <- MDuchi_pri_opt(train_data$X,train_data$y,  C=C, lambda=lambda, intercept = intercept)
  predicted_label <- predict(MDuchi_fit, test_data$X) 
  acc <- round(mean(predicted_label == test_data$y)*100,2)
  # acc_g <- round(c(mean(predicted_label[test_data$y == 1]==1), mean(predicted_label[test_data$y == 2]==2), mean(predicted_label[test_data$y == 3]==3))*100,2)
  title <- paste("MDuchi:",acc)
  g1.4 <- plot_decision_boundary(MDuchi_fit, print = F, title = title)

  figure <- ggarrange(g1.1, g1.2, g1.3, g1.4,
                      ncol=4, nrow = 1, common.legend = TRUE, legend="bottom")
    
  
  print(annotate_figure(figure,
                        top = text_grob(paste("Sep=",sep,sep=""), color = "red", face = "bold", size = 14)
  ))
  
}


```

