    ---
title: "Plots"
author: "Xinwei"
date: "6/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(combinat)
```

## R Markdown

```{r,  include=FALSE}

rm(list=ls())

MDuchi <- function(gamma){
  s_gamma1 <- sort(gamma[c(2,3)], decreasing = T)
  s_gamma2 <- sort(gamma[c(1,3)], decreasing = T)
  s_gamma3 <- sort(gamma[c(1,2)], decreasing = T)

  L1 <- max(0,(s_gamma1[1]-gamma[1]+1)/2, ((s_gamma1[1]-gamma[1]+1)/3+ (s_gamma1[2]-gamma[1]+1)/3))
  L2 <- max(0,(s_gamma2[1]-gamma[2]+1)/2, ((s_gamma2[1]-gamma[2]+1)/3+ (s_gamma2[2]-gamma[2]+1)/3))
  L3 <- max(0,(s_gamma3[1]-gamma[3]+1)/2, ((s_gamma3[1]-gamma[3]+1)/3+ (s_gamma3[2]-gamma[3]+1)/3))

  return(c(L1,L2,L3))
}


# gamma =matrix(runif(6000,-3,3),ncol=3)
permn(c(1,2,3))

MDuchi(c(0,0,1))

gamma1 = rbind(c(0,0,1),c(-1, .5,1.5),c(-2, 1,2),c(-3, 1.5,2.5),c(-4, 2,3),c(-5, 2.5,3.5),c(-6, 3,4), 
               c(-.5,-.5,2),c(-1,-1,3),c(-1.5,-1.5,4),c(-2,-2,5),c(-2.5,-2.5,6),c(-3,-3,7))

gamma <- do.call(rbind,lapply(permn(c(1,2,3)), function(x){gamma1[,x]}))

gamma <- t(apply(gamma,MARGIN=1, FUN = function(x){ y <- x + rep((1- sum(x))/3,3)}))
xyz_gamma <- t(apply(gamma, MARGIN=1, FUN = function(x){ 1-x }))
L_MDuchi <- t(apply(gamma,MARGIN=1,FUN=MDuchi))
# L_MDuchi

m <- list( symbol = 200, size = 5, line = list( color = toRGB("yellow"), width = 2 ) ) 
m1 <- list( symbol = "triangle", color="black", sizemod = "diameter", size = 5, line = list( color = "black", width = 2 ) )
xyz_gamma[10,]

fig <- plot_ly(x = L_MDuchi[,1], y = L_MDuchi[,2], z = L_MDuchi[,3]) %>%
  add_trace(marker = m1, type = "scatter3d", mode = "text+markers", 
            name ="original",   linetypes = NULL) %>%
  add_trace(x = xyz_gamma[,1], y = xyz_gamma[,2], z = xyz_gamma[,3], marker = m, type = "scatter3d", mode = "text+markers", 
            name = "projected",linetypes = NULL) %>% 
  add_trace(x = rbind(L_MDuchi[10,], xyz_gamma[10,])[,1], y = rbind(L_MDuchi[10,],xyz_gamma[10,])[,2], z = rbind(L_MDuchi[10,],xyz_gamma[10,])[,3],
                                                               type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)


for(i in 1:nrow(xyz_gamma)){
  fig <- fig %>% add_trace(x = rbind(L_MDuchi[i,], xyz_gamma[i,])[,1], y = rbind(L_MDuchi[i,],xyz_gamma[i,])[,2], z = rbind(L_MDuchi[i,], xyz_gamma[i,])[,3],
                         type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)
}

fig <- fig %>% layout(title="MDuchi", scene = list(xaxis = list(title = 'L1'),
                               yaxis = list(title = 'L2'),
                               zaxis = list(title = 'L3')))

```

```{r}
fig
```

```{r,  include=FALSE}

New1 <- function(gamma){
  s_gamma <- sort(gamma, decreasing = T)
  S <- max(0, s_gamma[1]-1, (s_gamma[1]+s_gamma[2]-1)/2)
  L1 <- 1-gamma[1] + S
  L2 <-  1-gamma[2] + S
  L3 <- max(gamma[1],0)  + max(gamma[2],0)
  return(c(L1,L2,L3))
}

gamma1 = rbind(c(0,0), c(-1, 0), c(-2, 0), c(-3, 0), c(-4, 0),  c(-5, 0), c(-6,0),
               c(0,-1), c(0,-2), c(0,-3), c(0,-4), c(0,-5), c(0,-6),
               c(1,0), c(1.5,.5),c(2,1),c(2.5,1.5),c(3,2),c(3.5,2.5),
               c(1,-1), c(1,-2),c(1,-3),c(1,-4),c(1,-5),c(1,-6),
               c(0,1), c(.5,1.5),c(1,2),c(1.5,2.5),c(2,3),c(2.5,3.5),
               c(-1,1), c(-2,1),c(-3,1),c(-4,1),c(-5,1),c(-6,1)
            )


gamma2 = rbind(c(0,0), c(-.5,-.5),c(-1,-1),c(-1.5,-1.5),c(-2,-2),c(-2.5,-2.5),c(-3,-3),c(-3.5,-3.5),
               c(1,0), c(2,0), c(3,0), c(4,0), c(5,0), c(6,0),
               c(0,1), c(0,2), c(0,3), c(0,4), c(0,5), c(0,6)
               )


gamma=rbind(gamma1,gamma2)

xyz_gamma <- 1-cbind(gamma, 1-rowSums(gamma))

L_New1 <- t(apply(gamma,MARGIN=1,FUN=New1))


m <- list( symbol = 200, size = 5, line = list( color = toRGB("yellow"), width = 2 ) ) 
m1 <- list( symbol = "triangle", color="black", sizemod = "diameter", size = 5, line = list( color = "black", width = 2 ) )

fig <- plot_ly(x = L_New1[,1], y = L_New1[,2], z = L_New1[,3]) %>%
  add_trace(marker = m1, type = "scatter3d", mode = "text+markers", 
            name ="original",   linetypes = NULL) %>%
  add_trace(x = xyz_gamma[,1], y = xyz_gamma[,2], z = xyz_gamma[,3], marker = m, type = "scatter3d", mode = "text+markers", 
            name = "projected",linetypes = NULL)

for(i in 1:nrow(xyz_gamma)){
  fig <- fig %>% add_trace(x = rbind(L_New1[i,], xyz_gamma[i,])[,1], y = rbind(L_New1[i,],xyz_gamma[i,])[,2], z = rbind(L_New1[i,], xyz_gamma[i,])[,3],
                           type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)
}

fig <- fig %>% layout(title="New1", scene = list(xaxis = list(title = 'L1'),
                                                yaxis = list(title = 'L2'),
                                                zaxis = list(title = 'L3')))


```

```{r}
fig
```


```{r,  include=FALSE}
New3 <- function(gamma){
  L1 <- max(0, 1- gamma[1], (gamma[2]-gamma[1]+1)/2)
  L2 <- max(0, 1- gamma[2], (gamma[1]-gamma[2]+1)/2)
  L3 <- max(gamma[1],0)  + max(gamma[2],0)
  return(c(L1,L2,L3))
}


gamma1 = rbind(c(0,0), c(-1, 0), c(-2, 0), c(-3, 0), c(-4, 0),  c(-5, 0),  c(-6, 0),
               c(0,-1), c(0,-2), c(0,-3), c(0,-4), c(0,-5),c(0,-6),
               c(1,0), c(1.5,.5),c(2,1),c(2.5,1.5),c(3,2),c(3.5,2.5),c(4,3),
               c(1,-1), c(1,-2),c(1,-3),c(1,-4),c(1,-5),c(1,-6),
               c(0,1), c(.5,1.5),c(1,2),c(1.5,2.5),c(2,3),c(2.5,3.5),c(3,4),
               c(-1,1), c(-2,1),c(-3,1),c(-4,1),c(-5,1),c(-6,1))

t(apply(gamma1[,1:2],MARGIN=1,FUN=New3))

gamma2 = rbind(c(0,0), c(-.5,-.5),c(-1,-1),c(-1.5,-1.5),c(-2,-2),c(-2.5,-2.5),c(-3,-3),c(-3.5,-3.5),
               c(1,0), c(2,-1), c(3,-2), c(4,-3), c(5,-4), c(6,-5),
               c(0,1), c(-1,2), c(-2,3), c(-3,4), c(-4,5), c(-5,6),
               c(0,2),c(0,3),c(0,4),c(0,5),c(0,6),c(0,7),
               c(2,0),c(3,0),c(4,0),c(5,0),c(6,0),c(7,0))
t(apply(gamma2[,1:2],MARGIN=1,FUN=New3))



gamma=rbind(gamma1,gamma2)

xyz_gamma <- 1-cbind(gamma, 1-rowSums(gamma))

L_New3 <- t(apply(gamma,MARGIN=1,FUN=New3))


m <- list( symbol = 200, size = 5, line = list( color = toRGB("yellow"), width = 2 ) ) 
m1 <- list( symbol = "triangle", color="black", sizemod = "diameter", size = 5, line = list( color = "black", width = 2 ) )

fig <- plot_ly(x = L_New3[,1], y = L_New3[,2], z = L_New3[,3]) %>%
  add_trace(marker = m1, type = "scatter3d", mode = "text+markers", 
            name ="original",   linetypes = NULL) %>%
  add_trace(x = xyz_gamma[,1], y = xyz_gamma[,2], z = xyz_gamma[,3], marker = m, type = "scatter3d", mode = "text+markers", 
            name = "projected",linetypes = NULL) %>% 
  add_trace(x = rbind(L_New3[10,], xyz_gamma[10,])[,1], y = rbind(L_New3[10,],xyz_gamma[10,])[,2], z = rbind(L_New3[10,],xyz_gamma[10,])[,3],
            type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)


for(i in 1:nrow(xyz_gamma)){
  fig <- fig %>% add_trace(x = rbind(L_New3[i,], xyz_gamma[i,])[,1], y = rbind(L_New3[i,],xyz_gamma[i,])[,2], z = rbind(L_New3[i,], xyz_gamma[i,])[,3],
                           type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)
}

fig <- fig %>% layout(title="New3", scene = list(xaxis = list(title = 'L1'),
                                                 yaxis = list(title = 'L2'),
                                                 zaxis = list(title = 'L3')))

```

```{r}
fig
```
