---
title: "Plots"
author: "Xinwei"
date: "6/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r,  include=FALSE}
library(plotly)

rm(list=ls())


MDuchi <- function(gamma){
  s_gamma1 <- sort(gamma[c(2,3)], decreasing = T)
  s_gamma2 <- sort(gamma[c(1,3)], decreasing = T)
  s_gamma3 <- sort(gamma[c(1,2)], decreasing = T)

  L1 <- max(0,(s_gamma1[1]-gamma[1]+1)/2, ((s_gamma1[1]-gamma[1]+1)/3+ (s_gamma1[2]-gamma[1]+1)/3))
  L2 <- max(0,(s_gamma2[1]-gamma[2]+1)/2, ((s_gamma2[1]-gamma[2]+1)/3+ (s_gamma2[2]-gamma[2]+1)/3))
  L3 <- max(0,(s_gamma3[1]-gamma[3]+1)/2, ((s_gamma3[1]-gamma[3]+1)/3+ (s_gamma3[2]-gamma[3]+1)/3))

  return(c(L1,L2,L3))
}


gamma =matrix(runif(600,-2,2),ncol=3)
gamma <- t(apply(gamma,MARGIN=1, FUN = function(x){ y <- x + rep((1- sum(x))/3,3)}))

xyz_gamma <- t(apply(gamma, MARGIN=1, FUN = function(x){ 1-x }))
L_MDuchi <- t(apply(gamma,MARGIN=1,FUN=MDuchi))

L_MDuchi_data <- as.data.frame(rbind(L_MDuchi,xyz_gamma))

L_MDuchi_data$color <- rowSums(L_MDuchi_data)


m <- list( symbol = 200, size = 5, line = list( color = toRGB("yellow"), width = 2 ) ) 
m1 <- list( symbol = "triangle", color="black", sizemod = "diameter", size = 5, line = list( color = "black", width = 2 ) )


fig <- plot_ly(x = L_MDuchi[,1], y = L_MDuchi[,2], z = L_MDuchi[,3]) %>%
  add_trace(marker = m1, type = "scatter3d", mode = "text+markers", 
            name ="original",   linetypes = NULL) %>%
  add_trace(x = xyz_gamma[,1], y = xyz_gamma[,2], z = xyz_gamma[,3], marker = m, type = "scatter3d", mode = "text+markers", 
            name = "projected",linetypes = NULL) %>% 
  add_trace(x = rbind(L_MDuchi[10,], xyz_gamma[10,])[,1], y = rbind(L_MDuchi[10,],xyz_gamma[10,])[,2], z = rbind(L_MDuchi[10,],xyz_gamma[10,])[,3],
                                                               type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)


for(i in 1:nrow(xyz_gamma)){
  fig <- fig %>% add_trace(x = rbind(L_MDuchi[i,], xyz_gamma[i,])[,1], y = rbind(L_MDuchi[i,],xyz_gamma[i,])[,2], z = rbind(L_MDuchi[i,], xyz_gamma[i,])[,3],
                         type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)
}

fig <- fig %>% layout(title="MDuchi")


```

```{r}
fig
```

```{r,  include=FALSE}

Duchi <- function(gamma){
  s_gamma <- sort(gamma, decreasing = T)
  g <- max(s_gamma[1]-1, (s_gamma[1]+s_gamma[2]-1)/2,  (s_gamma[1]+s_gamma[2] + s_gamma[3]-1)/3)
  return(c(1-gamma[1]+g,
           1-gamma[2]+g,
           1-gamma[3]+g))
}
# 
gamma =matrix(runif(600,-2,2),ncol=3)

gamma <- t(apply(gamma,MARGIN=1, FUN = function(x){ y <- x + rep((1- sum(x))/3,3)}))
L_Duchi <- t(apply(gamma,MARGIN=1,FUN=Duchi))

proj <- function(L){
  x <- L[2] + L[3] - 2*L[1] - 2
  y <- L[1] + L[3] - 2*L[2] - 2
  z <- L[1] + L[2] - 2*L[3] - 2
  return(-c(x,y,z)/3)
}

xyz_gamma  <- t(apply(gamma, MARGIN=1, FUN = function(x){ 1-x }))

L_Duchi_proj <- t(apply(L_Duchi, MARGIN = 1, FUN = proj))

L_Duchi_data <- as.data.frame(rbind(L_Duchi,L_Duchi_proj))
  
L_Duchi_data$color <- rowSums(L_Duchi_data)

m <- list( symbol = 200, size = 5, line = list( color = toRGB("yellow"), width = 2 ) ) 
m1 <- list( symbol = "triangle", color="black", sizemod = "diameter", size = 5, line = list( color = "black", width = 2 ) )

fig <- plot_ly(x = L_Duchi[,1], y = L_Duchi[,2], z = L_Duchi[,3]) %>%
  add_trace(marker = m1, type = "scatter3d", mode = "text+markers", 
            name ="original",   linetypes = NULL) %>%
  add_trace(x = xyz_gamma[,1], y = xyz_gamma[,2], z = xyz_gamma[,3], marker = m, type = "scatter3d", mode = "text+markers", 
            name = "projected",linetypes = NULL) %>% 
  add_trace(x = rbind(L_Duchi[10,], xyz_gamma[10,])[,1], y = rbind(L_Duchi[10,],xyz_gamma[10,])[,2], z = rbind(L_Duchi[10,],xyz_gamma[10,])[,3],
            type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)


for(i in 1:nrow(xyz_gamma)){
  fig <- fig %>% add_trace(x = rbind(L_Duchi[i,], xyz_gamma[i,])[,1], y = rbind(L_Duchi[i,],xyz_gamma[i,])[,2], z = rbind(L_Duchi[i,], xyz_gamma[i,])[,3],
                           type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)
}
fig <- fig %>% layout( title="Duchi")

```

```{r}
fig
```


```{r,  include=FALSE}
New1 <- function(gamma){
  s_gamma <- sort(gamma, decreasing = T)
  S <- max(0, s_gamma[1]-1, (s_gamma[1]+s_gamma[2]-1)/2)
  L1 <- 1-gamma[1] + S
  L2 <-  1-gamma[2] + S
  L3 <- max(gamma[1],0)  + max(gamma[2],0)
  return(c(L1,L2,L3))
}

gamma =matrix(runif(400,-2,2),ncol=2)

xyz_gamma <- 1-cbind(gamma, 1-rowSums(gamma))

L_New1 <- t(apply(gamma,MARGIN=1,FUN=New1))

L_New1_data <- as.data.frame(rbind(L_New1,xyz_gamma))

L_New1_data$color <- rowSums(L_New1_data)

m <- list( symbol = 200, size = 5, line = list( color = toRGB("yellow"), width = 2 ) ) 
m1 <- list( symbol = "triangle", color="black", sizemod = "diameter", size = 5, line = list( color = "black", width = 2 ) )

fig <- plot_ly(x = L_New1[,1], y = L_New1[,2], z = L_New1[,3]) %>%
  add_trace(marker = m1, type = "scatter3d", mode = "text+markers", 
            name ="original",   linetypes = NULL) %>%
  add_trace(x = xyz_gamma[,1], y = xyz_gamma[,2], z = xyz_gamma[,3], marker = m, type = "scatter3d", mode = "text+markers", 
            name = "projected",linetypes = NULL) %>% 
  add_trace(x = rbind(L_New1[10,], xyz_gamma[10,])[,1], y = rbind(L_New1[10,],xyz_gamma[10,])[,2], z = rbind(L_New1[10,],xyz_gamma[10,])[,3],
            type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)


for(i in 1:nrow(xyz_gamma)){
  fig <- fig %>% add_trace(x = rbind(L_New1[i,], xyz_gamma[i,])[,1], y = rbind(L_New1[i,],xyz_gamma[i,])[,2], z = rbind(L_New1[i,], xyz_gamma[i,])[,3],
                           type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)
}

fig <- fig %>% layout(title="New1")
  
fig
```

```{r}
fig
```

```{r,  include=FALSE}

New3 <- function(gamma){
  L1 <- max(0, 1- gamma[1], (gamma[2]-gamma[1]+1)/2)
  L2 <- max(0, 1- gamma[2], (gamma[1]-gamma[2]+1)/2)
  L3 <- max(gamma[1],0)  + max(gamma[2],0)
  return(c(L1,L2,L3))
}

# gamma =matrix(runif(400,-3,3),ncol=2)

xyz_gamma <- 1-cbind(gamma, 1-rowSums(gamma))

L_New3 <- t(apply(gamma,MARGIN=1,FUN=New3))

L_New3_data <- as.data.frame(rbind(L_New3,xyz_gamma))

L_New3_data$color <- rowSums(L_New3_data)


m <- list( symbol = 200, size = 5, line = list( color = toRGB("yellow"), width = 2 ) ) 
m1 <- list( symbol = "triangle", color="black", sizemod = "diameter", size = 5, line = list( color = "black", width = 2 ) )

fig <- plot_ly(x = L_New3[,1], y = L_New3[,2], z = L_New3[,3]) %>%
  add_trace(marker = m1, type = "scatter3d", mode = "text+markers", 
            name ="original",   linetypes = NULL) %>%
  add_trace(x = xyz_gamma[,1], y = xyz_gamma[,2], z = xyz_gamma[,3], marker = m, type = "scatter3d", mode = "text+markers", 
            name = "projected",linetypes = NULL) %>% 
  add_trace(x = rbind(L_New3[10,], xyz_gamma[10,])[,1], y = rbind(L_New3[10,],xyz_gamma[10,])[,2], z = rbind(L_New3[10,],xyz_gamma[10,])[,3],
            type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)


for(i in 1:nrow(xyz_gamma)){
  fig <- fig %>% add_trace(x = rbind(L_New3[i,], xyz_gamma[i,])[,1], y = rbind(L_New3[i,],xyz_gamma[i,])[,2], z = rbind(L_New3[i,], xyz_gamma[i,])[,3],
                           type = "scatter3d", mode = "lines", name = "lines", showlegend = FALSE)
}

fig <- fig %>% layout(title="New3")

fig

```

```{r}
fig
```
