---
title: "Summary of Simulations"
author: "Xinwei"
date: "7/28/2020"
output: 
 html_document:
     toc: true
     toc_depth: 3   
     theme: united
     number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
library(CVXR)
library(MASS)
library(R.matlab)
library(e1071)
library(kernlab)
library(ggpubr)
library(truncnorm)
library(ggplot2)
rm(list=ls())
setwd("~/Desktop/Multiclass Classification/MSVM Code")
source("primary form functions.R")

source("kernel primary form functions.R")


plot_circle_boundary <- function(models, X,y, title = NULL, xlim =NULL, ylim = NULL, rule = "simple_max"){
  X_dat <- as.data.frame(X)
  colnames(X_dat) <- c("x","y")
  X_dat$class <- as.factor(y)
  if(is.null(xlim)){
    xlim = c( round(min(X_dat$x,X_dat$y),2)-.01, round(max(X_dat$x,X_dat$y),2)+.01)
  }
  if(is.null(ylim)){
    ylim = c( round(min(X_dat$x,X_dat$y),2)-.01, round(max(X_dat$x,X_dat$y),2)+.01)
  }
  
  nd.r0 = seq(from = 1.05, 1.15, length.out = 30)
  nd.r1 = seq(from = 0.85, 0.9, length.out = 30)
  nd.r2 = seq(from = 0.7, 0.75, length.out = 30)
  nd.r3 = seq(from = 0.55, 0.6, length.out = 30)
  nd.r4 = seq(from = 0.4, 0.45, length.out = 30)
  nd.r5 = seq(from = 0.25, 0.3, length.out = 30)
  nd.theta = seq(from = 0, 2*pi, length.out = 500)
  nd.x = cbind(cos(nd.theta), sin(nd.theta))
  circ.theta = seq(from = 0, 2*pi, length.out = 2000)
  circ.x = cbind(cos(circ.theta), sin(circ.theta))
  circ.nd = as.data.frame(rbind(1.04*circ.x, 1.16*circ.x))
  colnames(circ.nd) <- c("x","y")
  
  nd0 = as.data.frame(do.call(rbind,lapply(nd.r0, function(r){r*nd.x})))
  nd1 = as.data.frame(do.call(rbind,lapply(nd.r1, function(r){r*nd.x})))
  nd2 = as.data.frame(do.call(rbind,lapply(nd.r2, function(r){r*nd.x})))
  nd3 = as.data.frame(do.call(rbind,lapply(nd.r3, function(r){r*nd.x})))
  nd4 = as.data.frame(do.call(rbind,lapply(nd.r4, function(r){r*nd.x})))
  nd5 = as.data.frame(do.call(rbind,lapply(nd.r5, function(r){r*nd.x})))

  nd0$class <- rep(predict(models[[1]], nd.x, rule = rule), 30)
  nd1$class <- rep(predict(models[[2]], nd.x, rule = rule), 30)
  nd2$class <- rep(predict(models[[3]], nd.x, rule = rule), 30)
  nd3$class <- rep(predict(models[[4]], nd.x, rule = rule), 30)
  nd4$class <- rep(predict(models[[5]], nd.x, rule = rule), 30)
  nd5$class <- rep(predict(models[[6]], nd.x, rule = rule), 30)
  
  nd <-  rbind(nd0,nd1,nd2,nd3,nd4,nd5)
  colnames(nd) <- c("x","y","class")
  nd$class <- as.factor(nd$class)
  # seg1 <- 0.97*data.frame(x1 = c(0,0,0), x2 = c(0,1,cos(11/10*pi)), y1 = c(0,0,0), y2 = c(1,0,sin(11/10*pi)))
   seg1 <- 1.16*data.frame(x1 = c(0,0,0), x2 = c(cos(0),cos(10/15*pi),cos(20/15*pi)), y1 = c(0,0,0), y2 = c(sin(0),sin(10/15*pi),sin(20/15*pi)))
  
  plt <- ggplot(nd, aes(x=x, y=y, color = class)) +
    geom_point( shape = 20) +
    geom_point(data = X_dat, size = 1) +
    geom_point(data = circ.nd, size = .3, colour = "black") +
    geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = seg1,  size = 1,linetype = 1, color="black") +
    scale_x_continuous(limits = xlim, expand=c(0,0)) +
    scale_y_continuous(limits = ylim, expand=c(0,0)) +
    ggtitle(title) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                            panel.background = element_blank(), axis.line = element_blank(),
                            axis.ticks = element_blank(),
                            axis.text.x = element_blank(),
                            axis.text.y = element_blank(),
                            plot.title = element_text(hjust = 0.5)) + 
    scale_color_manual(values=c("1" ="red","2"= "green", "3"="blue"))
  return(plt)
}


plot_ridge_batch <- function(X,y,C_list, intercept){
    
  g1 <- plot_circle_boundary(c(list(WW_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept)),
    lapply(C_list, function(C){WW_pri_opt(X,y_noise,C,intercept = intercept)})), X, y_noise, title = "WW")
  g2 <- plot_circle_boundary(c(list(CS_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept)),
    lapply(C_list, function(C){CS_pri_opt(X,y_noise,C,intercept = intercept)})), X, y_noise, title = "CS")
  g3 <- plot_circle_boundary(c(list(Duchi_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept)),
    lapply(C_list, function(C){Duchi_pri_opt(X,y_noise,C,intercept = intercept)})), X, y_noise, title = "Duchi")
  g4 <- plot_circle_boundary(c(list(MDuchi_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept)),
    lapply(C_list, function(C){MDuchi_pri_opt(X,y_noise,C,intercept = intercept)})), X, y_noise, title = "MDuchi")
  
  new1_models_b1 <- c(list(New1_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=1)),           lapply(C_list, function(C){New1_pri_opt(X,y_noise,C,intercept = intercept, base_class = 1)}))
  new1_models_b2 <- c(list(New1_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=2)),
      lapply(C_list, function(C){New1_pri_opt(X,y_noise,C,intercept = intercept, base_class = 2)}))
  new1_models_b3 <- c(list(New1_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=3)),           lapply(C_list, function(C){New1_pri_opt(X,y_noise,C,intercept = intercept, base_class = 3)}))

  g6.1 <- plot_circle_boundary(new1_models_b1, X, y_noise, title = "New1,base1,dagger", rule = "dagger")
  g6.2 <- plot_circle_boundary(new1_models_b2, X, y_noise, title = "New1,base2,dagger", rule = "dagger")
  g6.3 <- plot_circle_boundary(new1_models_b3, X, y_noise, title = "New1,base3,dagger", rule = "dagger")
  g6.4 <- NULL
  new3_models_b1 <- c(list(New3_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=1)),           lapply(C_list, function(C){New3_pri_opt(X,y_noise,C,intercept = intercept, base_class = 1)}))
  new3_models_b2 <- c(list(New3_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=2)),
      lapply(C_list, function(C){New3_pri_opt(X,y_noise,C,intercept = intercept, base_class = 2)}))
  new3_models_b3 <- c(list(New3_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=3)),           lapply(C_list, function(C){New3_pri_opt(X,y_noise,C,intercept = intercept, base_class = 3)}))


  g8.1 <- plot_circle_boundary(new3_models_b1, X, y_noise, title = "New3,base1,dagger", rule = "dagger")
  g8.2 <- plot_circle_boundary(new3_models_b2, X, y_noise, title = "New3,base2,dagger", rule = "dagger")
  g8.3 <- plot_circle_boundary(new3_models_b3, X, y_noise, title = "New3,base3,dagger", rule = "dagger")
  g8.4 <- NULL
  
  g9 <- plot_circle_boundary(c(list(OVA_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept)),                 lapply(C_list, function(C){OVA_pri_opt(X,y_noise,C,intercept = intercept)})), X, y_noise, title = "OVA")
  g10 <- tryCatch({plot_circle_boundary(c(list(LLW_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept)),       lapply(C_list, function(C){LLW_pri_opt(X,y_noise,C,intercept = intercept)})), X, y_noise, title = "LLW")}, error = function(e){NULL})
  g11 <- plot_circle_boundary(c(list(MSVM8_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept)), 
      lapply(C_list, function(C){MSVM8_pri_opt(X,y_noise,C,intercept = intercept)})), X, y_noise, title = "MSVM8")
  g12 <- NULL
  msvm_models_b1 <- c(list(MSVM7_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=1)),        lapply(C_list, function(C){MSVM7_pri_opt(X,y_noise,C,intercept = intercept, base_class = 1)}))
  msvm_models_b2 <- c(list(MSVM7_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=2)),        lapply(C_list, function(C){MSVM7_pri_opt(X,y_noise,C,intercept = intercept, base_class = 2)}))
  msvm_models_b3 <- c(list(MSVM7_pri_opt(X,y_noise,C=1,lambda=0,intercept = intercept, base_class=3)),         lapply(C_list, function(C){MSVM7_pri_opt(X,y_noise,C,intercept = intercept, base_class = 3)}))
  g14.1 <- plot_circle_boundary(msvm_models_b1, X, y_noise, title = "MSVM7,base1,dagger", rule = "dagger")
  g14.2 <- plot_circle_boundary(msvm_models_b2, X, y_noise, title = "MSVM7,base2,dagger", rule = "dagger")
  g14.3 <- plot_circle_boundary(msvm_models_b3, X, y_noise, title = "MSVM7,base3,dagger", rule = "dagger")
  g14.4 <- NULL

    ggarrange(g1, g2, g3,g4, g6.1,g6.2,g6.3,g6.4, g8.1,g8.2,g8.3,g8.4, g9,g10,g11,g12, 
              g14.1,g14.2,g14.3,g14.4, ncol=4, nrow=5, common.legend = TRUE, legend="bottom")


}

```


# Truncated Normal
##  n = 1000, prob I


```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- rtruncnorm(1, a=0, b=10, mean = 5, sd = 5/3)
    }else if(z==2){
      xz <- rtruncnorm(1, a=10, b=20, mean = 15, sd = 5/3)
    }else if(z==3){
      xz <- rtruncnorm(1, a=20, b=30, mean = 25, sd = 5/3)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1, prob= c(.45, .4, .15))
    }else if(z==2){
      y = sample(c(1,2,3), size=1, prob= c(.15, .45, .4))
    }else if(z==3){
      y = sample(c(1,2,3), size=1, prob= c(.4, .15, .45))
    }
    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1, prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1, prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1, prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))

  X <- 1.2*rbind(dat[,1:2], dat1[,1:2])
  y <- c(dat[,3],dat1[,3])
  list(X=X,y=y)
}
set.seed(422)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = T)

```





##  n = 1000, prob II

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=0, b=10, mean = 5, sd = 5/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=10, b=20, mean = 15, sd = 5/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=20, b=30, mean = 25, sd = 5/3)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    # if(z==1){
    #   y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    # }else if(z==2){
    #   y = sample(c(1,2,3), size=1,prob= c(.15, .45, .4))
    # }else if(z==3){
    #    y = sample(c(1,2,3), size=1,prob= c(.4, .15, .45))
    # }
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    }
    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))
  
  # X <- dat[,1:2]
  # y <- dat[,3]

  X <- 1.2*rbind(dat[,1:2], dat1[,1:2])
  y <- c(dat[,3],dat1[,3])
  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = T)

```



##  n = 1000, prob I, intercept = F

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=0, b=10, mean = 5, sd = 5/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=10, b=20, mean = 15, sd = 5/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=20, b=30, mean = 25, sd = 5/3)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.15, .45, .4))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.4, .15, .45))
    }
    # if(z==1){
    #   y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    # }else if(z==2){
    #   y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    # }else if(z==3){
    #    y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    # }
    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))
  
  # X <- dat[,1:2]
  # y <- dat[,3]

  X <- 1.2*rbind(dat[,1:2], dat1[,1:2])
  y <- c(dat[,3],dat1[,3])
  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = F)

```



##  n = 1000, prob II, intercept = F

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=0, b=10, mean = 5, sd = 5/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=10, b=20, mean = 15, sd = 5/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=20, b=30, mean = 25, sd = 5/3)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    # if(z==1){
    #   y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    # }else if(z==2){
    #   y = sample(c(1,2,3), size=1,prob= c(.15, .45, .4))
    # }else if(z==3){
    #    y = sample(c(1,2,3), size=1,prob= c(.4, .15, .45))
    # }
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    }
    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))
  
  # X <- dat[,1:2]
  # y <- dat[,3]

  X <- 1.2*rbind(dat[,1:2], dat1[,1:2])
  y <- c(dat[,3],dat1[,3])
  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = F)

```




# Uniform
##  n = 1000, prob I


```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 10)
    }else if(z==2){
      xz <- runif(1, min = 10, max = 20)
    }else if(z==3){
      xz <- runif(1, min = 20, max = 30)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1, prob= c(.45, .4, .15))
    }else if(z==2){
      y = sample(c(1,2,3), size=1, prob= c(.15, .45, .4))
    }else if(z==3){
      y = sample(c(1,2,3), size=1, prob= c(.4, .15, .45))
    }
    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1, prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1, prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1, prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))

  X <- 1.2*rbind(dat[,1:2], dat1[,1:2])
  y <- c(dat[,3],dat1[,3])
  list(X=X,y=y)
}
set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = T)

```





##  n = 1000, prob II

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 10)
    }else if(z==2){
      xz <- runif(1, min = 10, max = 20)
    }else if(z==3){
      xz <- runif(1, min = 20, max = 30)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    # if(z==1){
    #   y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    # }else if(z==2){
    #   y = sample(c(1,2,3), size=1,prob= c(.15, .45, .4))
    # }else if(z==3){
    #    y = sample(c(1,2,3), size=1,prob= c(.4, .15, .45))
    # }
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    }
    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))
  
  # X <- dat[,1:2]
  # y <- dat[,3]

  X <- 1.2*rbind(dat[,1:2], dat1[,1:2])
  y <- c(dat[,3],dat1[,3])
  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = T)

```



##  n = 1000, prob I, intercept = F

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
   if(z==1){
      xz <- runif(1, min = 0, max = 10)
    }else if(z==2){
      xz <- runif(1, min = 10, max = 20)
    }else if(z==3){
      xz <- runif(1, min = 20, max = 30)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.15, .45, .4))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.4, .15, .45))
    }
    # if(z==1){
    #   y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    # }else if(z==2){
    #   y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    # }else if(z==3){
    #    y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    # }
    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))
  
  # X <- dat[,1:2]
  # y <- dat[,3]

  X <- 1.2*rbind(dat[,1:2], dat1[,1:2])
  y <- c(dat[,3],dat1[,3])
  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = F)

```



##  n = 1000, prob II, intercept = F

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 10)
    }else if(z==2){
      xz <- runif(1, min = 10, max = 20)
    }else if(z==3){
      xz <- runif(1, min = 20, max = 30)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    # if(z==1){
    #   y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    # }else if(z==2){
    #   y = sample(c(1,2,3), size=1,prob= c(.15, .45, .4))
    # }else if(z==3){
    #    y = sample(c(1,2,3), size=1,prob= c(.4, .15, .45))
    # }
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    }
    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))
  
  # X <- dat[,1:2]
  # y <- dat[,3]

  X <- 1.2*rbind(dat[,1:2], dat1[,1:2])
  y <- c(dat[,3],dat1[,3])
  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = F)

```


# Uniform Unenhanced
##  n = 1000, prob I


```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 10)
    }else if(z==2){
      xz <- runif(1, min = 10, max = 20)
    }else if(z==3){
      xz <- runif(1, min = 20, max = 30)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1, prob= c(.45, .4, .15))
    }else if(z==2){
      y = sample(c(1,2,3), size=1, prob= c(.15, .45, .4))
    }else if(z==3){
      y = sample(c(1,2,3), size=1, prob= c(.4, .15, .45))
    }
    return(c(x,y))
  }))

  X <- 1.2*dat[,1:2]
  y <- dat[,3]
  list(X=X,y=y)
}
set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = T)

```





##  n = 1000, prob II

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 10)
    }else if(z==2){
      xz <- runif(1, min = 10, max = 20)
    }else if(z==3){
      xz <- runif(1, min = 20, max = 30)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    }
    return(c(x,y))
  }))
  

  X <- 1.2*dat[,1:2]
  y <- dat[,3]

  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = T)

```



##  n = 1000, prob I, intercept = F

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
   if(z==1){
      xz <- runif(1, min = 0, max = 10)
    }else if(z==2){
      xz <- runif(1, min = 10, max = 20)
    }else if(z==3){
      xz <- runif(1, min = 20, max = 30)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.45, .4, .15))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.15, .45, .4))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.4, .15, .45))
    }

    return(c(x,y))
  }))
   t <- sample(c(1,2,3), size = n/4, replace = T)
    dat1 <- t(sapply(t, function(z){
    if(z==1){
      # xz <- runif(1, min = 0, max = 1)
      xz <- rtruncnorm(1, a=4, b=6, mean = 5, sd = 1/3)
    }else if(z==2){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=14, b=16, mean = 15, sd = 1/3)
    }else if(z==3){
      # xz <- runif(1, min = 5, max = 6)
      xz <- rtruncnorm(1, a=24, b=26, mean = 25, sd = 1/3)
    }
     x = c(cos(xz*pi/15), sin(xz*pi/15))
    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.8, .1, .1))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.1, .8, .1))
    }else if(z==3){
      y = sample(c(1,2,3), size=1,prob= c(.1, .1, .8))
    }
    return(c(x,y))
  }))
  
  X <- 1.2*dat[,1:2]
  y <- dat[,3]

  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = F)

```



##  n = 1000, prob II, intercept = F

```{r fig.width=12, fig.height= 15, echo = F}

generate_noise_circle <- function(n){

  t <- sample(c(1,2,3), size = n, replace = T)
  dat <- t(sapply(t, function(z){
    if(z==1){
      xz <- runif(1, min = 0, max = 10)
    }else if(z==2){
      xz <- runif(1, min = 10, max = 20)
    }else if(z==3){
      xz <- runif(1, min = 20, max = 30)
    }
    x = c(cos(xz*pi/15), sin(xz*pi/15))

    if(z==1){
      y = sample(c(1,2,3), size=1,prob= c(.4, .3, .3))
    }else if(z==2){
      y = sample(c(1,2,3), size=1,prob= c(.3, .4, .3))
    }else if(z==3){
       y = sample(c(1,2,3), size=1,prob= c(.3, .3, .4))
    }
    return(c(x,y))
  }))
    
  X <- 1.2*dat[,1:2]
  y <- dat[,3]

  list(X=X,y=y)
}


set.seed(12)
n <- 800

dat <- generate_noise_circle(n)
X <- dat$X
y_noise <- dat$y
C_list <- 10^seq(1, -3, length.out = 5)

plot_ridge_batch(X,y_noise, C_list, intercept = F)

```



