---
title: "Two examples of decision boundary 0622"
author: "Xinwei"
date: "6/22/2020"
output: html_document
---

```{r setup, include=FALSE}
library(CVXR)
library(MASS)
library(nnet)
# rm(list = ls())
setwd("~/Desktop/Multiclass Classification/MSVM Code")
source("primary form functions.R")
source("Dual form functions.R")

#########Toy Example    
set.seed(123)

n = 400
Sigma <- matrix(c(3,-1,-1,2), nrow=2)
# Sigma <- matrix(c(10,0,0,1), nrow=2)
```

## Case 1

```{r cars}
X1 <- mvrnorm(n,c(-6,6),diag(2,2))
X2 <-  mvrnorm(n,c(5,5),matrix(c(3,-1,-1,2), nrow=2))
X3 <- mvrnorm(n,c(4,-2),diag(0.5,2))
X4 <- mvrnorm(n,c(-4,-4),matrix(c(4,-.5,-.5,2), nrow=2))

X <- rbind(X1,X2,X3,X4)
y <- c(rep(1,nrow(X1)),rep(2,nrow(X2)),rep(3,nrow(X3)),rep(4,nrow(X3)))

C = 1

plot_decision_boundary(X,y,beta = WW_pri_opt(X,y,C), title = "WW")
plot_decision_boundary(X,y,beta = CS_pri_opt(X,y,C), title = "CS")
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = MDuchi_pri_opt(X,y,C), title = "Mduchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, dagger", dagger_rule_w = T)
plot_decision_boundary(X,y,beta = New3_pri_opt(X,y,C), title = "New3, 0")
plot_decision_boundary(X,y,beta = New3_pri_opt(X,y,C), title = "New3, dagger", dagger_rule_w = T)

plot_decision_boundary(X,y,beta = OVA_pri_opt(X,y,C), title = "OVA")
plot_decision_boundary(X,y,beta = LLW_pri_opt(X,y,C=.1), title = "LLW")
plot_decision_boundary(X,y,beta = MSVM7_pri_opt(X,y,C), title = "Modifed LLW, 0")
plot_decision_boundary(X,y,beta = MSVM7_pri_opt(X,y,C), title = "Modifed LLW, dagger", dagger_rule_s = T)
plot_decision_boundary(X,y,beta = MSVM8_pri_opt(X,y,C), title = "MSVM8")

```

## Case 2

```{r pressure, echo=FALSE}
set.seed(1233)
n = 400
Sigma <- diag(1,2)
X1 <- mvrnorm(n,c(-4,7),Sigma)
X2 <- mvrnorm(n,c(7,0),Sigma)
X3 <- mvrnorm(n,c(0,0),Sigma)
X4 <- mvrnorm(n,c(-5,-5),Sigma)
X <- rbind(X1,X2,X3,X4)
y <- c(rep(1,nrow(X1)),rep(2,nrow(X2)),rep(3,nrow(X3)),rep(4,nrow(X3)))


C = 100

plot_decision_boundary(X,y,beta = WW_pri_opt(X,y,C), title = "WW")
plot_decision_boundary(X,y,beta = CS_pri_opt(X,y,C), title = "CS")
plot_decision_boundary(X,y,beta = Duchi_pri_opt(X,y,C), title = "Duchi")
plot_decision_boundary(X,y,beta = MDuchi_pri_opt(X,y,C), title = "Mduchi")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, 0")
plot_decision_boundary(X,y,beta = New1_pri_opt(X,y,C), title = "New1, dagger", dagger_rule_w = T)
plot_decision_boundary(X,y,beta = New3_pri_opt(X,y,C), title = "New3, 0")
plot_decision_boundary(X,y,beta = New3_pri_opt(X,y,C), title = "New3, dagger", dagger_rule_w = T)

plot_decision_boundary(X,y,beta = OVA_pri_opt(X,y,C), title = "OVA")
plot_decision_boundary(X,y,beta = LLW_pri_opt(X,y,C=.1), title = "LLW")
plot_decision_boundary(X,y,beta = MSVM7_pri_opt(X,y,C), title = "Modifed LLW, 0")
plot_decision_boundary(X,y,beta = MSVM7_pri_opt(X,y,C), title = "Modifed LLW, dagger", dagger_rule_s = T)
plot_decision_boundary(X,y,beta = MSVM8_pri_opt(X,y,C), title = "MSVM8")


```
